"""Persistence model registry used by Alembic metadata discovery."""

from app.db.models.administration import DemoSeedRegistry, PaymentMethod, UserInvitation
from app.db.models.agenda import Appointment, AppointmentEvent, AppointmentResource
from app.db.models.audit import AuditEntry
from app.db.models.catalog import Item, ItemBranchAssignment, ItemCategory, UnitOfMeasure
from app.db.models.crm import (
    CrmActivity,
    CrmLead,
    CrmOpportunity,
    CrmSettings,
    CustomerCrmProfile,
)
from app.db.models.dashboard import Task
from app.db.models.finance import (
    FinanceAccount,
    FinanceBudget,
    FinanceExpense,
    FinanceFixedExpense,
    FinanceFixedExpensePayment,
    FinanceLiability,
    FinanceManualIncome,
)
from app.db.models.foundation import (
    Branch,
    LegalEntity,
    LegalEntityIdentity,
    LegalEntityRegionalRule,
    ModuleDefinition,
    ModuleEntitlement,
    RegionalPack,
    RegionalRuleVersion,
    Workspace,
)
from app.db.models.hr import (
    EmployeeDebt,
    EmployeeDebtPayment,
    EmployeeHrProfile,
    HrDocumentRecord,
    HrLeaveRequest,
)
from app.db.models.identity import (
    AccessScope,
    AuthSession,
    Permission,
    PlatformUser,
    Role,
    RoleAssignment,
    RolePermission,
    WorkspaceMembership,
)
from app.db.models.incidents import (
    Incident,
    IncidentActivity,
    IncidentAttachment,
    IncidentCounter,
    IncidentParticipant,
)
from app.db.models.inventory import (
    Asset,
    AssetCategory,
    InventoryItemProfile,
    InventoryMovement,
    InventoryMovementLine,
    InventoryStockBalance,
    InventoryWarehouse,
)
from app.db.models.master_data import (
    Attachment,
    Customer,
    CustomerBranchAssignment,
    Employee,
    EmployeeBranchAssignment,
    EmployeeSchedule,
    EmployeeSupervisor,
)
from app.db.models.pos import CashMovement, CashMovementLine, CashRegister
from app.db.models.purchasing import (
    PurchaseRequest,
    PurchaseRequestItem,
    PurchasingSettings,
    Supplier,
    SupplierBranchAssignment,
)
from app.db.models.sales import (
    CustomerPayment,
    CustomerReceivable,
    CustomerReceivableLine,
    PaymentProof,
    Sale,
    SaleLine,
    SalesDocumentCounter,
    SalesQuote,
    SalesQuoteLine,
)

__all__ = [
    "AccessScope",
    "Attachment",
    "Appointment",
    "AppointmentEvent",
    "AppointmentResource",
    "AuthSession",
    "AuditEntry",
    "Asset",
    "AssetCategory",
    "Branch",
    "CashMovement",
    "CashMovementLine",
    "CashRegister",
    "CrmActivity",
    "CrmLead",
    "CrmOpportunity",
    "CrmSettings",
    "Customer",
    "CustomerCrmProfile",
    "CustomerBranchAssignment",
    "CustomerPayment",
    "CustomerReceivable",
    "CustomerReceivableLine",
    "DemoSeedRegistry",
    "Employee",
    "EmployeeBranchAssignment",
    "EmployeeDebt",
    "EmployeeDebtPayment",
    "EmployeeHrProfile",
    "EmployeeSchedule",
    "EmployeeSupervisor",
    "FinanceAccount",
    "FinanceBudget",
    "FinanceExpense",
    "FinanceFixedExpense",
    "FinanceFixedExpensePayment",
    "FinanceLiability",
    "FinanceManualIncome",
    "HrDocumentRecord",
    "HrLeaveRequest",
    "Incident",
    "IncidentActivity",
    "IncidentAttachment",
    "IncidentCounter",
    "IncidentParticipant",
    "Item",
    "ItemBranchAssignment",
    "ItemCategory",
    "InventoryItemProfile",
    "InventoryMovement",
    "InventoryMovementLine",
    "InventoryStockBalance",
    "InventoryWarehouse",
    "LegalEntity",
    "LegalEntityIdentity",
    "LegalEntityRegionalRule",
    "ModuleDefinition",
    "ModuleEntitlement",
    "Permission",
    "PaymentMethod",
    "PaymentProof",
    "PlatformUser",
    "PurchaseRequest",
    "PurchaseRequestItem",
    "PurchasingSettings",
    "RegionalPack",
    "RegionalRuleVersion",
    "Role",
    "RoleAssignment",
    "RolePermission",
    "Sale",
    "SaleLine",
    "SalesDocumentCounter",
    "SalesQuote",
    "SalesQuoteLine",
    "Supplier",
    "SupplierBranchAssignment",
    "Task",
    "Workspace",
    "WorkspaceMembership",
    "UnitOfMeasure",
    "UserInvitation",
]
