import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'

const adminPassword = process.env.FULL_STACK_ADMIN_PASSWORD || 'full-stack-test-password-not-a-secret-2026'
const ownerPassword = 'Carwash-e2e!password-2026'

async function login(page, email, password) {
  await page.goto('/login')
  await page.getByTestId('login-email').fill(email)
  await page.getByTestId('login-password').fill(password)
  const response = page.waitForResponse((result) => result.url().endsWith('/auth/login') && result.request().method() === 'POST')
  await page.getByTestId('login-submit').click()
  return (await response).json()
}

test('Carwash configures, bills, settles, reverses and reconciles reports with scoped access', async ({ page, browser }) => {
  test.setTimeout(300_000)
  const operatorTokens = await login(page, 'backoffice@erp.dev', adminPassword)
  await expect(page).toHaveURL(/\/backoffice$/)
  await page.goto('/backoffice/companias')
  await page.getByRole('button', { name: 'Nueva compañía' }).click()
  const suffix = Date.now()
  const ownerEmail = `carwash-owner-${suffix}@example.com`
  await page.getByLabel('Nombre de compañía').fill(`Carwash test ${suffix}`)
  await page.getByLabel('Slug', { exact: true }).fill(`carwash-test-${suffix}`)
  await page.getByLabel('Email del propietario').fill(ownerEmail)
  await page.getByLabel('Nombre del propietario').fill('Owner Carwash Test')
  await page.getByLabel('Contraseña inicial').fill(ownerPassword)
  const created = page.waitForResponse((response) => response.url().endsWith('/backoffice/workspaces') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Crear compañía', exact: true }).click()
  const response = await created
  expect(response.status()).toBe(201)
  const workspace = await response.json()
  await expect(page).toHaveURL(new RegExp(`/backoffice/companias/${workspace.workspaceId}$`))
  const carwash = page.getByRole('button', { name: 'Carwash', exact: true })
  await expect(carwash).toHaveAttribute('aria-pressed', 'false')

  const ownerContext = await browser.newContext()
  const owner = await ownerContext.newPage()
  const writes = []
  owner.on('request', (request) => {
    if (/\/api\/v1\/(carwash|pos)\//.test(request.url()) && request.method() !== 'GET') writes.push(request.url())
  })
  try {
    const tokens = await login(owner, ownerEmail, ownerPassword)
    const headers = { Authorization: `Bearer ${tokens.accessToken}` }
    await expect(owner).toHaveURL(/\/dashboard$/)
    await owner.goto('/carwash')
    await expect(owner).toHaveURL(/\/dashboard$/)
    await expect(owner.getByTestId('nav-carwash')).toHaveCount(0)

    async function saveModules() {
      const saved = page.waitForResponse((result) => result.url().endsWith(`/workspaces/${workspace.workspaceId}`) && result.request().method() === 'PATCH')
      await page.getByRole('button', { name: 'Guardar plan y módulos' }).click()
      const result = await saved
      expect(result.status()).toBe(200)
      return result.json()
    }

    await carwash.click()
    await expect(carwash).toHaveAttribute('aria-pressed', 'true')
    expect((await saveModules()).enabledModules).toContain('carwash')
    await owner.goto('/carwash?tab=operativo&branchId=foreign-branch')
    await expect(owner.getByTestId('carwash-page')).toBeVisible()
    await expect(owner).not.toHaveURL(/foreign-branch/)
    await expect(owner.getByTestId('carwash-availability-notice')).toHaveCount(0)
    await expect(owner.getByTestId('carwash-new-wash')).toBeEnabled()
    for (const tab of ['comisiones', 'reportes', 'configuracion']) {
      await owner.getByTestId(`carwash-tab-${tab}`).click()
      await expect(owner.getByTestId(`carwash-tab-${tab}`)).toHaveAttribute('aria-selected', 'true')
      await expect(owner.getByTestId('carwash-page')).not.toContainText('Cliente de ejemplo')
    }
    await expect(owner.getByTestId('carwash-new-service')).toBeEnabled()
    expect(writes).toEqual([])

    const categoryResult = await owner.request.post('/api-backend/api/v1/catalog/categories', { headers, data: { name: 'Lavados de prueba' } })
    expect(categoryResult.status()).toBe(201)
    await owner.setViewportSize({ width: 1440, height: 1000 })
    const branchId = new URL(owner.url()).searchParams.get('branchId')
    await owner.getByTestId('carwash-new-service').click()
    await owner.getByRole('button', { name: 'Crear servicios', exact: true }).click()
    const modal = owner.getByTestId('carwash-service-modal')
    const names = ['Lavado básico de prueba', 'Lavado premium de prueba']
    for (const [index, name] of names.entries()) {
      if (index) await modal.getByRole('button', { name: 'Añadir otro servicio' }).click()
      const line = owner.getByTestId(`carwash-service-line-${index}`)
      await line.getByLabel('Nombre del servicio').fill(name)
      await line.getByRole('combobox', { name: `Categoría del servicio ${index + 1}` }).click()
      await owner.getByRole('option', { name: 'Lavados de prueba', exact: true }).click()
      await line.getByLabel('Precio sin impuestos').fill(index ? '850.50' : '400.00')
      await expect(line.getByLabel('Comisión lavador (%)')).toHaveValue('20')
      await expect(line.getByLabel('Comisión encargado (%)')).toHaveValue('5')
    }
    const evidence = path.resolve('../output/playwright')
    await mkdir(evidence, { recursive: true })
    await expect(modal).toHaveCSS('opacity', '1')
    await owner.getByTestId('carwash-service-fields').evaluate((element) => { element.scrollTop = 0 })
    await owner.screenshot({ path: path.join(evidence, 'carwash-phase1-create-desktop.png'), animations: 'disabled' })
    const creation = owner.waitForResponse((result) => result.url().endsWith('/carwash/services/batch') && result.request().method() === 'POST')
    await owner.getByTestId('carwash-save-services').click()
    const createdServices = await creation
    expect(createdServices.status()).toBe(201)
    const items = (await createdServices.json()).items
    expect(items).toHaveLength(2)
    const foreignWorkspace = await page.request.get(`/api-backend/api/v1/carwash/services/${items[0].id}`, { headers: { Authorization: `Bearer ${operatorTokens.accessToken}` } })
    expect(foreignWorkspace.status()).toBe(404)
    const repeat = await owner.request.post('/api-backend/api/v1/carwash/services/batch', { headers: { ...headers, 'Idempotency-Key': createdServices.request().headers()['idempotency-key'] }, data: createdServices.request().postDataJSON() })
    expect(repeat.status()).toBe(201)
    expect((await repeat.json()).items.map((item) => item.id)).toEqual(items.map((item) => item.id))
    await expect(modal).toHaveCount(0)
    await owner.reload()
    await expect(owner.getByTestId('carwash-services')).toContainText(names[0])
    await expect(owner.getByTestId('carwash-services')).toContainText(names[1])
    const inventory = await owner.request.get(`/api-backend/api/v1/inventory/items/${items[0].itemId}`, { headers })
    expect(inventory.status()).toBe(200)
    expect((await inventory.json()).salePrice).toBe('400.00')

    await owner.getByTestId('carwash-services').getByRole('button', { name: `Editar ${names[0]}`, exact: true }).click()
    await modal.getByLabel('Comisión lavador (%)').fill('30')
    await modal.getByLabel('Comisión encargado (%)').fill('8.25')
    await modal.getByLabel('Habilitado en esta sucursal').uncheck()
    await expect(modal.getByRole('link', { name: /Inventarios/ })).toHaveAttribute('target', '_blank')
    await owner.getByTestId('carwash-save-services').click()
    await expect(modal).toHaveCount(0)
    await expect(owner.getByTestId('carwash-services')).toContainText('Deshabilitado')
    const listing = await owner.request.get(`/api-backend/api/v1/carwash/services?branchId=${branchId}&enabled=false`, { headers })
    const disabled = (await listing.json()).items
    expect(disabled).toHaveLength(1)
    expect(disabled[0]).toMatchObject({ washerRate: '30.00', supervisorRate: '8.25' })

    const priceUpdate = await owner.request.patch(`/api-backend/api/v1/inventory/items/${items[0].itemId}`, { headers, data: { version: items[0].catalogVersion, salePrice: '425.50' } })
    expect(priceUpdate.status()).toBe(200)
    await owner.getByRole('button', { name: 'Actualizar servicios' }).click()
    await expect(owner.getByTestId('carwash-services')).toContainText('425.50')
    await owner.screenshot({ path: path.join(evidence, 'carwash-phase1-settings-desktop.png'), fullPage: true, animations: 'disabled' })

    await owner.setViewportSize({ width: 390, height: 844 })
    await owner.getByTestId('carwash-services-mobile').getByRole('button', { name: `Editar ${names[0]}`, exact: true }).click()
    await expect(modal.getByLabel('Comisión lavador (%)')).toHaveValue('30.00')
    await modal.getByLabel('Habilitado en esta sucursal').check()
    await expect(modal).toHaveCSS('opacity', '1')
    const bounds = await owner.getByTestId('carwash-save-services').boundingBox()
    expect(bounds.y + bounds.height).toBeLessThanOrEqual(844)
    await owner.getByTestId('carwash-service-fields').evaluate((element) => { element.scrollTop = 0 })
    await owner.screenshot({ path: path.join(evidence, 'carwash-phase1-edit-mobile.png'), animations: 'disabled' })
    await owner.getByTestId('carwash-save-services').click()
    await expect(modal).toHaveCount(0)
    await expect(owner.getByTestId('carwash-services-mobile')).not.toContainText('Deshabilitado')
    expect(await owner.getByTestId('carwash-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
    await owner.getByTestId('carwash-services-mobile').scrollIntoViewIfNeeded()
    await owner.screenshot({ path: path.join(evidence, 'carwash-phase1-settings-mobile.png'), animations: 'disabled' })

    await owner.route('**/api/v1/carwash/services?*', (route) => route.abort('failed'))
    await owner.getByRole('button', { name: 'Actualizar servicios' }).click()
    await expect(owner.getByText('Esta copia es de solo lectura hasta recuperar la conexión.')).toBeVisible()
    await expect(owner.getByTestId('carwash-new-service')).toBeDisabled()
    await expect(owner.getByTestId('carwash-services-mobile')).toContainText(names[0])
    await owner.unroute('**/api/v1/carwash/services?*')
    await owner.getByRole('button', { name: 'Reintentar', exact: true }).click()
    await expect(owner.getByTestId('carwash-new-service')).toBeEnabled()

    const commercial = await inventory.json()
    const catalogService = await owner.request.post('/api-backend/api/v1/inventory/services', { headers: { ...headers, 'Idempotency-Key': `catalog-carwash-${suffix}` }, data: { name: 'Lavado cortesía del catálogo', categoryId: items[0].categoryId, unitOfMeasureId: commercial.unitOfMeasure.id, salePrice: '0.00', taxRate: '0.00', branchIds: [branchId] } })
    expect(catalogService.status()).toBe(201)
    await owner.getByTestId('carwash-new-service').click()
    await modal.getByRole('checkbox', { name: /Lavado cortesía del catálogo/ }).check()
    await expect(modal.getByLabel('Comisión lavador (%)')).toHaveValue('20')
    const enableCatalog = owner.waitForResponse((result) => result.url().endsWith('/carwash/services/batch') && result.request().method() === 'POST')
    await owner.getByTestId('carwash-save-services').click()
    const linked = await enableCatalog
    expect(linked.status()).toBe(201)
    const added = (await linked.json()).items[0]
    expect(added.itemId).toBe((await catalogService.json()).id)
    expect(added.salePrice).toBe('0.00')
    items.push(added)
    await expect(modal).toHaveCount(0)
    await owner.getByLabel('Buscar servicios configurados').fill('cortesía')
    await owner.getByRole('button', { name: 'Buscar', exact: true }).click()
    await expect(owner).toHaveURL(/serviceSearch=/)
    await owner.reload()
    await expect(owner.getByLabel('Buscar servicios configurados')).toHaveValue('cortesía')
    await expect(owner.getByTestId('carwash-services-mobile')).toContainText('Lavado cortesía del catálogo')
    await expect(owner.getByTestId('carwash-services-mobile')).not.toContainText(names[0])
    expect(writes.every((url) => url.includes('/carwash/services'))).toBe(true)

    await verifyOperations(owner, { headers, branchId, evidence, suffix, foreignToken: operatorTokens.accessToken })
    expect(writes.every((url) => url.includes('/carwash/'))).toBe(true)
    await verifyCheckout(owner, { headers, branchId, evidence })
    await verifyCommissions(owner, { headers, branchId, evidence })
    await verifyReports(owner, { headers, branchId, evidence })
    await verifyResponsiveRelease(owner, { branchId, evidence })
    const beforeDisable = await historySnapshot(owner, { headers, branchId })

    await carwash.click()
    await expect(carwash).toHaveAttribute('aria-pressed', 'false')
    expect((await saveModules()).enabledModules).not.toContain('carwash')
    const denied = await owner.request.get(`/api-backend/api/v1/carwash/services?branchId=${branchId}`, { headers })
    expect(denied.status()).toBe(403)
    for (const resource of ['washes', 'commissions', 'settlements', 'reports', 'indicators']) {
      const blocked = await owner.request.get(`/api-backend/api/v1/carwash/${resource}?branchId=${branchId}`, { headers })
      expect(blocked.status()).toBe(403)
    }
    await owner.reload()
    await expect(owner).toHaveURL(/\/dashboard$/)
    await expect(owner.getByTestId('carwash-page')).toHaveCount(0)
    await expect(owner.getByTestId('nav-carwash')).toHaveCount(0)
    await carwash.click()
    await saveModules()
    const retained = await owner.request.get(`/api-backend/api/v1/carwash/services?branchId=${branchId}`, { headers })
    expect(retained.status()).toBe(200)
    expect((await retained.json()).items.map((item) => item.id).sort()).toEqual(items.map((item) => item.id).sort())
    expect(await historySnapshot(owner, { headers, branchId })).toEqual(beforeDisable)
    await carwash.click()
    await saveModules()
  } finally {
    await ownerContext.close()
  }
})

async function verifyOperations(page, { headers, branchId, evidence, suffix, foreignToken }) {
  const api = '/api-backend/api/v1'
  const employee = await page.request.post(`${api}/employees`, { headers, data: { employeeNumber: `CW-${suffix}`, firstName: 'Ana', lastName: 'Operaciones', position: 'Lavador', hireDate: '2026-01-01', branchIds: [branchId] } })
  expect(employee.status()).toBe(201)
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByTestId('carwash-tab-operativo').click()
  await page.getByTestId('carwash-new-wash').click()
  const form = page.getByTestId('carwash-wash-modal')
  await form.getByLabel('Placa', { exact: true }).fill('CW-2026')
  await form.getByLabel('Marca / modelo').fill('Toyota Corolla')
  await form.getByLabel('Color', { exact: true }).fill('Azul')
  await form.getByRole('button', { name: 'Crear cliente rápido' }).click()
  const customerModal = page.getByTestId('customer-form-modal')
  await customerModal.getByTestId('customer-field-name').fill(`Cliente lavado ${suffix}`)
  await customerModal.getByRole('button', { name: /Crear cliente|Guardar cliente/ }).click()
  await expect(customerModal).toHaveCount(0)
  await expect(form.getByLabel('Placa', { exact: true })).toHaveValue('CW-2026')
  await expect(form.getByRole('combobox', { name: 'Cliente', exact: true })).toContainText(`Cliente lavado ${suffix}`)
  async function select(label, name) {
    const combobox = form.getByRole('combobox', { name: label, exact: true })
    await combobox.click()
    const listId = await combobox.getAttribute('aria-controls')
    await page.locator(`[id="${listId}"]`).getByRole('option', { name, exact: true }).click()
  }
  await select('Añadir servicio', 'Lavado básico de prueba')
  await select('Añadir servicio', 'Lavado cortesía del catálogo')
  await select('Lavador', 'Ana Operaciones')
  await select('Encargado', 'Ana Operaciones')
  await expect(form.getByRole('link', { name: /Configurar o crear servicios/ })).toHaveAttribute('target', '_blank')
  await expect(form).toHaveCSS('opacity', '1')
  await page.getByTestId('carwash-wash-fields').evaluate((element) => { element.scrollTop = 0 })
  await page.screenshot({ path: path.join(evidence, 'carwash-phase2-reception-desktop.png'), animations: 'disabled' })
  let firstRequest
  await page.route('**/carwash/washes', async (route) => {
    if (route.request().method() !== 'POST') return route.continue()
    firstRequest = route.request()
    const response = await route.fetch()
    expect(response.status()).toBe(201)
    await route.abort('failed')
  }, { times: 1 })
  await page.getByTestId('carwash-save-wash').click()
  await expect(form.getByText(/No se confirmó el resultado/)).toBeVisible()
  await expect(form.getByLabel('Placa', { exact: true })).toBeDisabled()
  const creation = page.waitForResponse((response) => response.url().endsWith('/carwash/washes') && response.request().method() === 'POST')
  await page.getByTestId('carwash-save-wash').click()
  const created = await creation
  expect(created.status()).toBe(201)
  expect(created.request().headers()['idempotency-key']).toBe(firstRequest.headers()['idempotency-key'])
  const wash = await created.json()
  expect(wash.lines).toHaveLength(2)
  expect(wash.total).toBe('502.09')
  expect(wash.washerId).toBe(wash.supervisorId)
  await expect(form).toHaveCount(0)
  const foreign = await page.request.get(`${api}/carwash/washes/${wash.id}`, { headers: { Authorization: `Bearer ${foreignToken}` } })
  expect(foreign.status()).toBe(404)
  const table = page.getByTestId('carwash-washes')
  await expect(table).toContainText('CW-2026')
  await expect(table.getByRole('button', { name: 'Completar', exact: true })).toBeDisabled()
  const list = await page.request.get(`${api}/carwash/washes?branchId=${branchId}`, { headers })
  expect((await list.json()).totalItems).toBe(1)
  await page.screenshot({ path: path.join(evidence, 'carwash-phase2-operational-desktop.png'), fullPage: true, animations: 'disabled' })

  await table.getByRole('button', { name: 'Editar', exact: true }).click()
  await form.getByLabel('Placa', { exact: true }).fill('CW-2027')
  await page.getByTestId('carwash-save-wash').click()
  await expect(form).toHaveCount(0)
  await table.getByRole('button', { name: 'Iniciar', exact: true }).click()
  await page.getByTestId('carwash-action-modal').getByRole('button', { name: 'Iniciar lavado', exact: true }).click()
  await expect(table).toContainText('Lavando')
  await page.getByTestId('carwash-search').fill('CW-2027')
  await page.getByRole('button', { name: 'Buscar', exact: true }).click()
  await expect(page).toHaveURL(/search=CW-2027/)
  await page.reload()
  await expect(page.getByTestId('carwash-search')).toHaveValue('CW-2027')
  await expect(table).toContainText('Lavando')

  await page.setViewportSize({ width: 390, height: 844 })
  const cards = page.getByTestId('carwash-washes-mobile')
  await cards.getByRole('button', { name: 'Editar', exact: true }).click()
  await expect(form).toHaveCSS('opacity', '1')
  const bounds = await page.getByTestId('carwash-save-wash').boundingBox()
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(844)
  await page.getByTestId('carwash-wash-fields').evaluate((element) => { element.scrollTop = 0 })
  await page.screenshot({ path: path.join(evidence, 'carwash-phase2-reception-mobile.png'), animations: 'disabled' })
  await form.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await cards.getByRole('button', { name: 'Cancelar', exact: true }).click()
  const action = page.getByTestId('carwash-action-modal')
  await action.getByLabel('Motivo de cancelación').fill('Cliente solicita retirar el vehículo')
  await action.getByRole('button', { name: 'Confirmar cancelación' }).click()
  await expect(action).toHaveCount(0)
  await expect(cards).toContainText('Cancelado')
  await cards.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByTestId('carwash-wash-detail')).toContainText('Cliente solicita retirar el vehículo')
  await page.getByTestId('carwash-wash-detail').getByRole('button', { name: 'Cerrar', exact: true }).click()
  expect(await page.getByTestId('carwash-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await cards.scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase2-operational-mobile.png'), animations: 'disabled' })
  await page.route('**/carwash/washes?*', (route) => route.abort('failed'))
  await page.getByRole('button', { name: 'Actualizar lavados' }).click()
  await expect(page.getByText('Esta copia es de solo lectura hasta recuperar la conexión.')).toBeVisible()
  await expect(page.getByTestId('carwash-new-wash')).toBeDisabled()
  await expect(cards).toContainText('CW-2027')
  await page.unroute('**/carwash/washes?*')
  await page.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(page.getByTestId('carwash-new-wash')).toBeEnabled()
  expect(errors).toEqual([])
}


async function verifyCheckout(page, { headers, branchId, evidence }) {
  const api = '/api-backend/api/v1'
  const previous = await page.request.get(`${api}/carwash/washes?branchId=${branchId}`, { headers })
  const original = (await previous.json()).items[0]
  const makeWash = async (plate) => {
    const created = await page.request.post(`${api}/carwash/washes`, { headers: { ...headers, 'Idempotency-Key': crypto.randomUUID() }, data: { branchId, customerId: original.customerId, plate, washerId: original.washerId, supervisorId: original.supervisorId, serviceIds: original.lines.map((line) => line.serviceConfigId) } })
    expect(created.status()).toBe(201)
    const wash = await created.json()
    const started = await page.request.post(`${api}/carwash/washes/${wash.id}/start`, { headers: { ...headers, 'Idempotency-Key': crypto.randomUUID() }, data: { version: wash.version } })
    expect(started.status()).toBe(200)
    return started.json()
  }
  const wash = await makeWash('CW-CASH-3')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`/carwash?tab=operativo&branchId=${branchId}&search=CW-CASH-3`)
  const table = page.getByTestId('carwash-washes')
  await table.getByRole('button', { name: 'Completar', exact: true }).click()
  const modal = page.getByTestId('carwash-checkout-modal')
  await expect(modal.getByText(/Necesitas una caja abierta/)).toBeVisible()
  await expect(page.getByTestId('carwash-confirm-checkout')).toBeDisabled()
  const register = await page.request.post(`${api}/pos/registers`, { headers: { ...headers, 'Idempotency-Key': crypto.randomUUID() }, data: { branchId, openingCash: '0.00' } })
  expect(register.status()).toBe(201)
  await modal.getByRole('button', { name: 'Actualizar caja' }).click()
  await modal.getByRole('button', { name: 'Efectivo', exact: true }).click()
  await modal.getByLabel('Valor del descuento').fill('10')
  await expect(page.getByTestId('carwash-confirm-checkout')).toBeEnabled()
  await expect(modal).toHaveCSS('opacity', '1')
  await page.screenshot({ path: path.join(evidence, 'carwash-phase3-checkout-desktop.png'), animations: 'disabled' })
  let first
  await page.route(`**/carwash/washes/${wash.id}/complete`, async (route) => { first = route.request(); const result = await route.fetch(); expect(result.status()).toBe(200); await route.abort('failed') }, { times: 1 })
  await page.getByTestId('carwash-confirm-checkout').click()
  await expect(modal.getByText(/No se confirmó la respuesta/)).toBeVisible()
  const completion = page.waitForResponse((response) => response.url().endsWith(`/washes/${wash.id}/complete`))
  await modal.getByRole('button', { name: 'Recuperar resultado' }).click()
  const response = await completion
  expect(response.status()).toBe(200)
  expect(response.request().headers()['idempotency-key']).toBe(first.headers()['idempotency-key'])
  const completed = await response.json()
  await expect(modal.getByText(`Factura ${completed.saleNumber}`, { exact: false })).toBeVisible()
  await modal.getByRole('button', { name: 'Cerrar y actualizar' }).click()
  await expect(table).toContainText('Completado')
  await table.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByTestId('carwash-wash-detail')).toContainText('Total facturado:')
  await page.getByTestId('carwash-wash-detail').getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.setViewportSize({ width: 320, height: 640 })
  const cards = page.getByTestId('carwash-washes-mobile')
  await cards.getByRole('button', { name: 'Anular', exact: true }).click()
  const action = page.getByTestId('carwash-action-modal')
  await action.getByLabel('Motivo de anulación').fill('Prueba de reverso coordinado')
  await action.getByRole('button', { name: 'Confirmar anulación' }).click()
  await expect(action).toHaveCount(0)
  await expect(cards).toContainText('Anulado')
  const sale = await page.request.get(`${api}/pos/sales/${completed.saleId}`, { headers })
  expect((await sale.json()).status).toBe('voided')

  const creditWash = await makeWash('CW-CREDIT-3')
  const method = await page.request.post(`${api}/payment-methods`, { headers, data: { code: `cwproof${Date.now()}`, name: 'Transferencia Carwash', channel: 'bank_transfer', settlementPolicy: 'pending_confirmation', affectsCashDrawer: false, requiresEvidence: true } })
  expect(method.status()).toBe(201)
  await page.goto(`/carwash?tab=operativo&branchId=${branchId}&search=CW-CREDIT-3`)
  await cards.getByRole('button', { name: 'Completar', exact: true }).click()
  await modal.getByRole('button', { name: 'Transferencia Carwash', exact: true }).click()
  for (const method of await page.getByTestId('carwash-payment-picker').getByRole('button').all()) {
    expect(await method.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  }
  await page.getByTestId('carwash-evidence-file').setInputFiles({ name: 'comprobante.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') })
  await expect(page.getByTestId('carwash-confirm-checkout')).toBeEnabled()
  const bounds = await page.getByTestId('carwash-confirm-checkout').boundingBox()
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(640)
  await expect(modal).toHaveCSS('opacity', '1')
  await page.screenshot({ path: path.join(evidence, 'carwash-phase3-checkout-mobile.png'), animations: 'disabled' })
  let checkoutCount = 0
  page.on('request', (request) => { if (request.url().endsWith(`/washes/${creditWash.id}/complete`)) checkoutCount += 1 })
  await page.route('**/receivables/*/proofs', async (route) => { const result = await route.fetch(); expect(result.status()).toBe(201); await route.abort('failed') }, { times: 1 })
  await page.getByTestId('carwash-confirm-checkout').click()
  await expect(modal.getByText(/La venta ya está guardada/)).toBeVisible()
  await modal.getByRole('button', { name: 'Reintentar comprobante' }).click()
  await expect(modal.getByText('Comprobante adjuntado.')).toBeVisible()
  expect(checkoutCount).toBe(1)
  await modal.getByRole('button', { name: 'Cerrar y actualizar' }).click()
  await expect(cards).toContainText('Pago en CxC')
  await cards.getByRole('button', { name: 'Ver detalle' }).click()
  await expect(page.getByTestId('carwash-wash-detail').getByRole('link', { name: 'Consultar cuenta por cobrar' })).toBeVisible()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase3-billing-mobile.png'), animations: 'disabled' })
  await page.getByTestId('carwash-wash-detail').getByRole('button', { name: 'Cerrar', exact: true }).click()
  const sales = await page.request.get(`${api}/pos/sales?branchId=${branchId}`, { headers })
  expect((await sales.json()).totalItems).toBe(2)
}

async function verifyCommissions(page, { headers, branchId, evidence }) {
  const api = '/api-backend/api/v1'
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`/carwash?tab=comisiones&branchId=${branchId}&commissionStatus=pending`)
  const table = page.getByTestId('carwash-commissions')
  await expect(table).toContainText('CW-CREDIT-3')
  await expect(table.getByRole('checkbox')).toHaveCount(4)
  const summaryResponse = await page.request.get(`${api}/carwash/commissions?branchId=${branchId}&status=pending`, { headers })
  const summary = await summaryResponse.json()
  expect(summary.summary.washes).toBe(1)
  for (const box of await table.getByRole('checkbox').all()) await box.check()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase4-commissions-desktop.png'), animations: 'disabled' })
  await page.getByTestId('carwash-open-settlement').click()
  const modal = page.getByTestId('carwash-settlement-modal')
  await expect(page.getByTestId('carwash-confirm-settlement')).toBeEnabled()
  await expect(modal).toHaveCSS('opacity', '1')
  await page.screenshot({ path: path.join(evidence, 'carwash-phase4-settlement-desktop.png'), animations: 'disabled' })
  let first
  await page.route('**/carwash/settlements', async (route) => {
    if (route.request().method() !== 'POST') { await route.continue(); return }
    first = route.request()
    const result = await route.fetch()
    expect(result.status()).toBe(201)
    await route.abort('failed')
  }, { times: 1 })
  await page.getByTestId('carwash-confirm-settlement').click()
  await expect(modal.getByText(/No se confirmó la respuesta/)).toBeVisible()
  const resultPromise = page.waitForResponse((response) => response.url().endsWith('/carwash/settlements') && response.request().method() === 'POST')
  await modal.getByRole('button', { name: 'Recuperar resultado' }).click()
  const result = await resultPromise
  expect(result.status()).toBe(201)
  expect(result.request().headers()['idempotency-key']).toBe(first.headers()['idempotency-key'])
  const settlement = await result.json()
  await expect(modal).toHaveCount(0)
  await expect(table.getByRole('checkbox')).toHaveCount(0)
  await expect(page.getByTestId('carwash-settlements')).toContainText('Vigente')
  const history = await page.request.get(`${api}/carwash/settlements?branchId=${branchId}`, { headers })
  expect((await history.json()).totalItems).toBe(1)
  const blocked = await page.request.post(`${api}/carwash/washes/${summary.items[0].washId}/void`, { headers: { ...headers, 'Idempotency-Key': crypto.randomUUID() }, data: { version: 3, reason: 'No anular comisiones pagadas' } })
  expect(blocked.status()).toBe(409)
  await page.setViewportSize({ width: 320, height: 640 })
  await page.getByTestId('carwash-settlements-mobile').getByRole('button', { name: 'Revertir', exact: true }).click()
  await modal.getByLabel('Motivo del reverso').fill('Corrección de liquidación en prueba')
  await page.getByTestId('carwash-settlement-fields').evaluate((element) => { element.scrollTop = element.scrollHeight })
  const reasonBounds = await modal.getByLabel('Motivo del reverso').boundingBox()
  const totalBounds = await page.getByTestId('carwash-settlement-total').boundingBox()
  expect(reasonBounds.y + reasonBounds.height).toBeLessThan(totalBounds.y)
  await expect(page.getByTestId('carwash-confirm-settlement')).toBeEnabled()
  const bounds = await page.getByTestId('carwash-confirm-settlement').boundingBox()
  expect(bounds.y + bounds.height).toBeLessThanOrEqual(640)
  await expect(modal).toHaveCSS('opacity', '1')
  await page.screenshot({ path: path.join(evidence, 'carwash-phase4-reversal-mobile.png'), animations: 'disabled' })
  await page.getByTestId('carwash-confirm-settlement').click()
  await expect(modal).toHaveCount(0)
  await expect(page.getByTestId('carwash-settlements-mobile')).toContainText('Revertida')
  await expect(page.getByTestId('carwash-commissions-mobile').getByRole('checkbox')).toHaveCount(4)
  const reversed = await page.request.get(`${api}/carwash/settlements/${settlement.id}`, { headers })
  expect((await reversed.json()).reversalMovementId).toBeTruthy()
  expect(await page.getByTestId('carwash-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.getByTestId('carwash-commissions-mobile').scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase4-commissions-mobile.png'), animations: 'disabled' })
  await page.route('**/carwash/commissions?*', (route) => route.abort('failed'))
  await page.getByRole('button', { name: 'Actualizar', exact: true }).click()
  await expect(page.getByText('Esta copia es de solo lectura hasta recuperar la conexión.')).toBeVisible()
  await expect(page.getByTestId('carwash-commissions-mobile').getByRole('checkbox').first()).toBeDisabled()
  await page.unroute('**/carwash/commissions?*')
}

async function verifyReports(page, { headers, branchId, evidence }) {
  const api = '/api-backend/api/v1/carwash'
  const errors = []
  const onError = (error) => errors.push(error.message)
  page.on('pageerror', onError)
  const response = await page.request.get(`${api}/reports?branchId=${branchId}`, { headers })
  expect(response.status()).toBe(200)
  const report = await response.json()
  const commissions = await (await page.request.get(`${api}/commissions?branchId=${branchId}&status=pending`, { headers })).json()
  const indicators = await (await page.request.get(`${api}/indicators?branchId=${branchId}`, { headers })).json()
  expect(report.totals.washes).toBe(1)
  expect(report.totals.billed).toBe(commissions.summary.billed)
  expect(report.totals.commissions).toBe(commissions.summary.commissions)
  expect(report.totals.serviceCount).toBe(2)
  expect(report.employees).toHaveLength(1)
  expect(report.employees[0].washes).toBe(1)
  expect(indicators.pendingCommissions).toBe(report.totals.commissions)
  expect(indicators.activeWashes).toBe(0)
  expect(report.daily.reduce((sum, row) => sum + Math.round(Number(row.billed) * 100), 0)).toBe(Math.round(Number(report.totals.billed) * 100))

  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto(`/carwash?tab=reportes&branchId=${branchId}`)
  await expect(page.getByTestId('carwash-report-from')).toHaveValue(report.dateFrom)
  await expect(page).toHaveURL(new RegExp(`dateFrom=${report.dateFrom}`))
  for (const chart of ['lines', 'donut', 'ranking']) await expect(page.getByTestId(`carwash-report-${chart}`).locator('.recharts-wrapper > svg.recharts-surface')).toBeVisible()
  await expect(page.getByTestId('carwash-report-services')).toContainText('Lavado cortesía del catálogo')
  await expect(page.getByTestId('carwash-report-billed')).toContainText(report.totals.billed)
  await page.screenshot({ path: path.join(evidence, 'carwash-phase5-reports-desktop.png'), fullPage: true, animations: 'disabled' })
  await page.getByTestId('carwash-report-ranking').scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase5-ranking-desktop.png'), animations: 'disabled' })
  await page.getByTestId('carwash-report-from').fill('2000-01-01')
  await page.getByTestId('carwash-report-to').fill('2000-01-31')
  await page.getByRole('button', { name: 'Aplicar período' }).click()
  await expect(page.getByText('No hay lavados completados en este período.')).toBeVisible()
  await expect(page.getByText('No hay servicios realizados en este período.')).toBeVisible()
  await expect(page.getByText('No hay comisiones devengadas en este período.')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('carwash-report-from')).toHaveValue('2000-01-01')
  await page.getByRole('button', { name: 'Mes actual' }).click()
  await expect(page.getByTestId('carwash-report-from')).toHaveValue(report.dateFrom)
  await expect(page.getByTestId('carwash-report-lines').locator('.recharts-wrapper > svg.recharts-surface')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByTestId('carwash-reports').evaluate((element) => element.scrollIntoView({ block: 'start' }))
  expect((await page.getByTestId('carwash-report-from').boundingBox()).width).toBeGreaterThan(140)
  expect((await page.getByTestId('carwash-report-to').boundingBox()).width).toBeGreaterThan(140)
  await page.screenshot({ path: path.join(evidence, 'carwash-phase5-reports-mobile.png'), fullPage: true, animations: 'disabled' })
  await page.getByTestId('carwash-report-donut').locator('..').scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase5-services-mobile.png'), animations: 'disabled' })
  await page.getByTestId('carwash-report-ranking').locator('..').scrollIntoViewIfNeeded()
  await page.screenshot({ path: path.join(evidence, 'carwash-phase5-ranking-mobile.png'), animations: 'disabled' })
  await page.getByText('Ver detalle diario', { exact: true }).click()
  await expect(page.getByTestId('carwash-report-daily-mobile')).toBeVisible()
  await page.getByText('Ver importes por empleado', { exact: true }).click()
  await expect(page.getByTestId('carwash-report-employees-mobile')).toContainText('Ana Operaciones')
  expect(await page.getByTestId('carwash-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.route('**/carwash/reports?*', (route) => route.abort('failed'))
  await expect(page.getByText('Mostrando la última copia disponible en memoria.')).toBeVisible({ timeout: 20000 })
  await expect(page.getByTestId('carwash-report-billed')).toContainText(report.totals.billed)
  await expect(page.getByTestId('carwash-report-period')).toContainText(report.dateFrom)
  await page.unroute('**/carwash/reports?*')
  await page.getByRole('button', { name: 'Reintentar', exact: true }).click()
  await expect(page.getByText('Datos sincronizados con la API.')).toBeVisible()
  expect(errors).toEqual([])
  page.off('pageerror', onError)
}

async function historySnapshot(page, { headers, branchId }) {
  const result = {}
  for (const resource of ['services', 'washes', 'commissions', 'settlements', 'reports', 'indicators']) {
    const response = await page.request.get(`/api-backend/api/v1/carwash/${resource}?branchId=${branchId}`, { headers })
    expect(response.status()).toBe(200)
    const data = await response.json()
    delete data.generatedAt
    result[resource] = data
  }
  const sales = await page.request.get(`/api-backend/api/v1/pos/sales?branchId=${branchId}`, { headers })
  expect(sales.status()).toBe(200)
  result.sales = await sales.json()
  return result
}

async function verifyResponsiveRelease(page, { branchId, evidence }) {
  for (const width of [1440, 390, 320]) {
    const height = width < 640 ? 640 : 1000
    await page.setViewportSize({ width, height })
    for (const tab of ['operativo', 'comisiones', 'reportes', 'configuracion']) {
      await page.goto(`/carwash?tab=${tab}&branchId=${branchId}`)
      await expect(page.getByRole('tabpanel').getByText('Datos sincronizados con la API.')).toBeVisible()
      expect(await page.getByTestId('carwash-page').evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
      expect(await page.locator('body').evaluate((element) => element.scrollWidth <= window.innerWidth)).toBe(true)
      await page.locator('main').evaluate((element) => { element.scrollTop = 0 })
      await page.screenshot({ path: path.join(evidence, `carwash-phase6-connected-${tab}-${width}.png`), animations: 'disabled' })
      await page.getByRole('tabpanel').scrollIntoViewIfNeeded()
      await page.screenshot({ path: path.join(evidence, `carwash-phase6-connected-${tab}-${width}-content.png`), animations: 'disabled' })
      if (tab === 'reportes') {
        expect((await page.getByTestId('carwash-report-from').boundingBox()).width).toBeGreaterThan(140)
        expect((await page.getByTestId('carwash-report-to').boundingBox()).width).toBeGreaterThan(140)
      }
      if (tab === 'configuracion' && width < 640) {
        await page.getByTestId('carwash-new-service').click()
        const modal = page.getByTestId('carwash-service-modal')
        await expect(modal.getByText('Cargando catálogo y configuración…')).toHaveCount(0)
        await expect(modal).toHaveCSS('opacity', '1')
        expect(await modal.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
        const bounds = await page.getByTestId('carwash-save-services').boundingBox()
        expect(bounds.y).toBeGreaterThan(0)
        expect(bounds.y + bounds.height).toBeLessThanOrEqual(height)
        await page.screenshot({ path: path.join(evidence, `carwash-phase6-service-modal-${width}.png`), animations: 'disabled' })
        await modal.getByRole('button', { name: 'Cerrar', exact: true }).click()
      }
    }
  }
}
