import assert from 'node:assert/strict'

const base = process.argv[2]
assert.ok(base, 'Provide the deployment URL')
const health = await fetch(`${base}/health`)
assert.equal(health.status, 200)
assert.equal((await health.text()).trim(), 'ok')
assert.match(health.headers.get('cache-control'), /no-store/)
const page = await fetch(`${base}/`)
assert.equal(page.status, 200)
assert.equal(page.headers.get('x-content-type-options'), 'nosniff')
assert.equal(page.headers.get('x-frame-options'), 'DENY')
assert.match(page.headers.get('cache-control'), /must-revalidate/)
const html = await page.text()
const deep = await fetch(`${base}/login`, { headers: { 'Sec-Fetch-Mode': 'navigate' } })
assert.equal(deep.status, 200)
assert.equal(await deep.text(), html)
const assets = [...html.matchAll(/(?:src|href)="(\/assets\/[^\"]+\.(?:js|css))"/g)].map(m => m[1])
assert.ok(assets.length >= 2)
for (const asset of assets) {
  const response = await fetch(`${base}${asset}`)
  assert.equal(response.status, 200)
  assert.match(response.headers.get('content-type'), asset.endsWith('.css') ? /text\/css/ : /javascript/)
  assert.match(response.headers.get('cache-control'), /immutable/)
  const body = await response.text()
  assert.ok(!body.includes('api.helios360erp.com'))
}
const missing = await fetch(`${base}/assets/nonexistent-migration-check.js`)
assert.equal(missing.status, 404)
console.log('PASS: health, SPA, security headers, cache, JS/CSS and missing asset')
