"""Add Terminal POS sales, cash-register, and receivable persistence.

Revision ID: 20260831_0013
Revises: 20260831_0012
Create Date: 2026-08-31

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260831_0013"
down_revision: str | Sequence[str] | None = "20260831_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_PERMISSION_CODES = (
    "sales.read",
    "sales.quote.manage",
    "pos.read",
    "pos.sell",
    "pos.discount.override",
    "pos.register.manage",
    "pos.cash.read",
    "pos.cash.manage",
    "pos.receivables.read",
    "pos.receivables.collect",
    "pos.receivables.manage",
    "pos.void",
)

_ROLE_PERMISSION_CODES = {
    "workspace_admin": _PERMISSION_CODES,
    "manager": _PERMISSION_CODES,
    "cashier": (
        "sales.read",
        "pos.read",
        "pos.sell",
        "pos.register.manage",
        "pos.cash.read",
        "pos.cash.manage",
        "pos.receivables.read",
        "pos.receivables.collect",
    ),
    "supervisor": (
        "sales.read",
        "pos.read",
        "pos.cash.read",
        "pos.receivables.read",
        "pos.receivables.collect",
        "pos.void",
    ),
    "seller": (
        "sales.read",
        "sales.quote.manage",
        "pos.read",
        "pos.sell",
    ),
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_document_counters",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("last_quote_value", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_sale_value", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "last_receivable_value", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_quote_value >= 0",
            name=op.f("ck_sales_document_counters_last_quote_value_non_negative"),
        ),
        sa.CheckConstraint(
            "last_receivable_value >= 0",
            name=op.f("ck_sales_document_counters_last_receivable_value_non_negative"),
        ),
        sa.CheckConstraint(
            "last_sale_value >= 0",
            name=op.f("ck_sales_document_counters_last_sale_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sales_document_counters_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_sales_document_counters")),
    )
    op.create_table(
        "cash_registers",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("opening_cash", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "cash_sales_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "receivable_payments_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "cash_income_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "cash_expense_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("expected_cash", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("actual_cash", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("difference", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("opened_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("opened_by_name", sa.String(length=200), nullable=False),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_by_membership_id", sa.Uuid(), nullable=True),
        sa.Column("closed_by_platform_user_id", sa.Uuid(), nullable=True),
        sa.Column("closed_by_name", sa.String(length=200), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("open_idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("open_request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("close_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("close_request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'open' AND closed_at IS NULL AND closed_by_membership_id IS NULL "
            "AND closed_by_platform_user_id IS NULL AND closed_by_name IS NULL "
            "AND expected_cash IS NULL AND actual_cash IS NULL AND difference IS NULL "
            "AND close_idempotency_key IS NULL AND close_request_fingerprint IS NULL) OR "
            "(status = 'closed' AND closed_at IS NOT NULL AND "
            "closed_by_membership_id IS NOT NULL AND closed_by_platform_user_id IS NOT NULL "
            "AND closed_by_name IS NOT NULL AND expected_cash IS NOT NULL "
            "AND actual_cash IS NOT NULL AND difference IS NOT NULL "
            "AND close_idempotency_key IS NOT NULL AND close_request_fingerprint IS NOT NULL)",
            name=op.f("ck_cash_registers_close_state_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'closed')", name=op.f("ck_cash_registers_status_values")
        ),
        sa.CheckConstraint(
            "cash_expense_amount >= 0",
            name=op.f("ck_cash_registers_cash_expense_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "cash_income_amount >= 0",
            name=op.f("ck_cash_registers_cash_income_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "cash_sales_amount >= 0", name=op.f("ck_cash_registers_cash_sales_amount_non_negative")
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name=op.f("ck_cash_registers_currency_code_length")
        ),
        sa.CheckConstraint(
            "char_length(open_idempotency_key) >= 8",
            name=op.f("ck_cash_registers_open_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(open_request_fingerprint) = 64",
            name=op.f("ck_cash_registers_open_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)",
            name=op.f("ck_cash_registers_currency_code_uppercase"),
        ),
        sa.CheckConstraint(
            "difference IS NULL OR difference = actual_cash - expected_cash",
            name=op.f("ck_cash_registers_difference_reconciles"),
        ),
        sa.CheckConstraint(
            "expected_cash IS NULL OR expected_cash = opening_cash + cash_sales_amount + "
            "receivable_payments_amount + cash_income_amount - cash_expense_amount",
            name=op.f("ck_cash_registers_expected_cash_reconciles"),
        ),
        sa.CheckConstraint(
            "opening_cash >= 0", name=op.f("ck_cash_registers_opening_cash_non_negative")
        ),
        sa.CheckConstraint(
            "receivable_payments_amount >= 0",
            name=op.f("ck_cash_registers_receivable_payments_amount_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_cash_registers_closed_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opened_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_cash_registers_opened_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_cash_registers_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "closed_by_membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_cash_registers_workspace_closer_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "opened_by_membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_cash_registers_workspace_opener_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_cash_registers_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_registers")),
        sa.UniqueConstraint(
            "workspace_id", "branch_id", "id", name="uq_cash_registers_workspace_branch_id"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_cash_registers_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "open_idempotency_key", name="uq_cash_registers_open_idempotency"
        ),
    )
    op.create_index(
        "ix_cash_registers_workspace_branch_opened",
        "cash_registers",
        ["workspace_id", "branch_id", "opened_at"],
        unique=False,
    )
    op.create_index(
        "uq_cash_registers_close_idempotency",
        "cash_registers",
        ["workspace_id", "close_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("close_idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "uq_cash_registers_open_branch",
        "cash_registers",
        ["workspace_id", "branch_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "sales_quotes",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("document_number", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default=sa.text("'quote'"), nullable=False),
        sa.Column("origin", sa.String(length=16), server_default=sa.text("'pos'"), nullable=False),
        sa.Column("status", sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_phone", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "discount_mode", sa.String(length=16), server_default=sa.text("'pct'"), nullable=False
        ),
        sa.Column(
            "discount_value",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "total", sa.Numeric(precision=14, scale=2), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method_code", sa.String(length=48), nullable=True),
        sa.Column("payment_method_name", sa.String(length=120), nullable=True),
        sa.Column("payment_channel", sa.String(length=24), nullable=True),
        sa.Column("settlement_policy", sa.String(length=24), nullable=True),
        sa.Column("affects_cash_drawer", sa.Boolean(), nullable=True),
        sa.Column("requires_evidence", sa.Boolean(), nullable=True),
        sa.Column("payment_reference", sa.String(length=160), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("creation_idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'open' AND closed_at IS NULL) OR "
            "(status <> 'open' AND closed_at IS NOT NULL)",
            name=op.f("ck_sales_quotes_status_closed_at_consistent"),
        ),
        sa.CheckConstraint(
            "(payment_method_id IS NULL AND payment_method_code IS NULL AND "
            "payment_method_name IS NULL AND payment_channel IS NULL AND "
            "settlement_policy IS NULL AND affects_cash_drawer IS NULL AND "
            "requires_evidence IS NULL) OR "
            "(payment_method_id IS NOT NULL AND payment_method_code IS NOT NULL AND "
            "payment_method_name IS NOT NULL AND payment_channel IS NOT NULL AND "
            "settlement_policy IS NOT NULL AND affects_cash_drawer IS NOT NULL AND "
            "requires_evidence IS NOT NULL)",
            name=op.f("ck_sales_quotes_payment_snapshot_consistent"),
        ),
        sa.CheckConstraint(
            "discount_mode <> 'pct' OR discount_value <= 100",
            name=op.f("ck_sales_quotes_discount_pct_range"),
        ),
        sa.CheckConstraint(
            "discount_mode IN ('pct', 'amount')", name=op.f("ck_sales_quotes_discount_mode_values")
        ),
        sa.CheckConstraint("kind IN ('quote', 'held')", name=op.f("ck_sales_quotes_kind_values")),
        sa.CheckConstraint("origin IN ('pos', 'crm')", name=op.f("ck_sales_quotes_origin_values")),
        sa.CheckConstraint(
            "status IN ('open', 'converted', 'cancelled', 'expired')",
            name=op.f("ck_sales_quotes_status_values"),
        ),
        sa.CheckConstraint(
            "char_length(creation_idempotency_key) >= 8",
            name=op.f("ck_sales_quotes_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name=op.f("ck_sales_quotes_currency_code_length")
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64", name=op.f("ck_sales_quotes_fingerprint_length")
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)",
            name=op.f("ck_sales_quotes_currency_code_uppercase"),
        ),
        sa.CheckConstraint(
            "discount_amount <= subtotal",
            name=op.f("ck_sales_quotes_discount_amount_within_subtotal"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_quotes_discount_amount_non_negative")
        ),
        sa.CheckConstraint(
            "discount_value >= 0", name=op.f("ck_sales_quotes_discount_value_non_negative")
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_sales_quotes_subtotal_non_negative")),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_sales_quotes_tax_amount_non_negative")),
        sa.CheckConstraint(
            "total = subtotal - discount_amount + tax_amount",
            name=op.f("ck_sales_quotes_total_reconciles"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_sales_quotes_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["created_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_sales_quotes_created_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_sales_quotes_updated_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_sales_quotes_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "customer_id"],
            ["customers.workspace_id", "customers.id"],
            name="fk_sales_quotes_workspace_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "payment_method_id"],
            ["payment_methods.workspace_id", "payment_methods.id"],
            name="fk_sales_quotes_workspace_payment_method",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sales_quotes_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_quotes")),
        sa.UniqueConstraint(
            "workspace_id", "creation_idempotency_key", name="uq_sales_quotes_workspace_idempotency"
        ),
        sa.UniqueConstraint(
            "workspace_id", "document_number", name="uq_sales_quotes_workspace_number"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_sales_quotes_workspace_id"),
    )
    op.create_index(
        "ix_sales_quotes_workspace_branch_status_updated",
        "sales_quotes",
        ["workspace_id", "branch_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_sales_quotes_workspace_customer_status",
        "sales_quotes",
        ["workspace_id", "customer_id", "status"],
        unique=False,
    )
    op.create_table(
        "sales_quote_lines",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("item_name", sa.String(length=160), nullable=False),
        sa.Column("item_sku", sa.String(length=64), nullable=True),
        sa.Column("item_type", sa.String(length=24), nullable=False),
        sa.Column("unit_symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("list_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_rate",
            sa.Numeric(precision=5, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_quote_lines_discount_amount_non_negative")
        ),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_sales_quote_lines_line_total_non_negative")
        ),
        sa.CheckConstraint(
            "list_price >= 0", name=op.f("ck_sales_quote_lines_list_price_non_negative")
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_sales_quote_lines_position_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_quote_lines_quantity_positive")),
        sa.CheckConstraint(
            "tax_amount >= 0", name=op.f("ck_sales_quote_lines_tax_amount_non_negative")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_sales_quote_lines_tax_rate_range")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_sales_quote_lines_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["items.workspace_id", "items.id"],
            name="fk_sales_quote_lines_workspace_item",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "quote_id"],
            ["sales_quotes.workspace_id", "sales_quotes.id"],
            name="fk_sales_quote_lines_workspace_quote",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sales_quote_lines_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_quote_lines")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_sales_quote_lines_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "quote_id", "position", name="uq_sales_quote_lines_position"
        ),
    )
    op.create_index(
        "ix_sales_quote_lines_workspace_item",
        "sales_quote_lines",
        ["workspace_id", "item_id"],
        unique=False,
    )
    op.create_index(
        "ix_sales_quote_lines_workspace_quote",
        "sales_quote_lines",
        ["workspace_id", "quote_id"],
        unique=False,
    )
    op.create_table(
        "sales",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("cash_register_id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=True),
        sa.Column("inventory_movement_id", sa.Uuid(), nullable=True),
        sa.Column("sale_number", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'completed'"), nullable=False
        ),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=True),
        sa.Column("customer_phone", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_mode", sa.String(length=16), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_code", sa.String(length=48), nullable=False),
        sa.Column("payment_method_name", sa.String(length=120), nullable=False),
        sa.Column("payment_channel", sa.String(length=24), nullable=False),
        sa.Column("settlement_policy", sa.String(length=24), nullable=False),
        sa.Column("affects_cash_drawer", sa.Boolean(), nullable=False),
        sa.Column("requires_evidence", sa.Boolean(), nullable=False),
        sa.Column("payment_reference", sa.String(length=160), nullable=True),
        sa.Column("sold_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("sold_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("sold_by_name", sa.String(length=200), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voided_by_platform_user_id", sa.Uuid(), nullable=True),
        sa.Column("void_reason", sa.String(length=1000), nullable=True),
        sa.Column("creation_idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("void_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("void_request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'completed' AND voided_at IS NULL AND "
            "voided_by_platform_user_id IS NULL AND void_reason IS NULL) OR "
            "(status = 'voided' AND voided_at IS NOT NULL AND "
            "voided_by_platform_user_id IS NOT NULL AND void_reason IS NOT NULL)",
            name=op.f("ck_sales_void_state_consistent"),
        ),
        sa.CheckConstraint(
            "discount_mode <> 'pct' OR discount_value <= 100",
            name=op.f("ck_sales_discount_pct_range"),
        ),
        sa.CheckConstraint(
            "discount_mode IN ('pct', 'amount')", name=op.f("ck_sales_discount_mode_values")
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'voided')", name=op.f("ck_sales_status_values")
        ),
        sa.CheckConstraint(
            "(void_idempotency_key IS NULL) = (void_request_fingerprint IS NULL)",
            name=op.f("ck_sales_void_idempotency_pair"),
        ),
        sa.CheckConstraint(
            "char_length(creation_idempotency_key) >= 8",
            name=op.f("ck_sales_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name=op.f("ck_sales_currency_code_length")
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64", name=op.f("ck_sales_fingerprint_length")
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)", name=op.f("ck_sales_currency_code_uppercase")
        ),
        sa.CheckConstraint(
            "discount_amount <= subtotal", name=op.f("ck_sales_discount_amount_within_subtotal")
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sales_discount_amount_non_negative")
        ),
        sa.CheckConstraint(
            "discount_value >= 0", name=op.f("ck_sales_discount_value_non_negative")
        ),
        sa.CheckConstraint("subtotal >= 0", name=op.f("ck_sales_subtotal_non_negative")),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_sales_tax_amount_non_negative")),
        sa.CheckConstraint(
            "total = subtotal - discount_amount + tax_amount",
            name=op.f("ck_sales_total_reconciles"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_sales_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["sold_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_sales_sold_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_sales_voided_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "cash_register_id"],
            ["cash_registers.workspace_id", "cash_registers.branch_id", "cash_registers.id"],
            name="fk_sales_workspace_register",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_sales_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "customer_id"],
            ["customers.workspace_id", "customers.id"],
            name="fk_sales_workspace_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "inventory_movement_id"],
            ["inventory_movements.workspace_id", "inventory_movements.id"],
            name="fk_sales_workspace_inventory_movement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "payment_method_id"],
            ["payment_methods.workspace_id", "payment_methods.id"],
            name="fk_sales_workspace_payment_method",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "quote_id"],
            ["sales_quotes.workspace_id", "sales_quotes.id"],
            name="fk_sales_workspace_quote",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "sold_by_membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_sales_workspace_seller_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sales_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("workspace_id", "branch_id", "id", name="uq_sales_workspace_branch_id"),
        sa.UniqueConstraint(
            "workspace_id", "creation_idempotency_key", name="uq_sales_workspace_idempotency"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_sales_workspace_id"),
        sa.UniqueConstraint("workspace_id", "sale_number", name="uq_sales_workspace_number"),
    )
    op.create_index(
        "ix_sales_workspace_branch_completed",
        "sales",
        ["workspace_id", "branch_id", "completed_at"],
        unique=False,
    )
    op.create_index(
        "ix_sales_workspace_customer_completed",
        "sales",
        ["workspace_id", "customer_id", "completed_at"],
        unique=False,
    )
    op.create_index(
        "uq_sales_workspace_inventory_movement",
        "sales",
        ["workspace_id", "inventory_movement_id"],
        unique=True,
        postgresql_where=sa.text("inventory_movement_id IS NOT NULL"),
    )
    op.create_index(
        "uq_sales_workspace_quote",
        "sales",
        ["workspace_id", "quote_id"],
        unique=True,
        postgresql_where=sa.text("quote_id IS NOT NULL"),
    )
    op.create_index(
        "uq_sales_workspace_void_idempotency",
        "sales",
        ["workspace_id", "void_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("void_idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "customer_receivables",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_number", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=True),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method_code", sa.String(length=48), nullable=True),
        sa.Column("payment_method_name", sa.String(length=120), nullable=True),
        sa.Column("payment_channel", sa.String(length=24), nullable=True),
        sa.Column("settlement_policy", sa.String(length=24), nullable=True),
        sa.Column("affects_cash_drawer", sa.Boolean(), nullable=True),
        sa.Column("requires_evidence", sa.Boolean(), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("customer_name", sa.String(length=200), nullable=False),
        sa.Column("customer_phone", sa.String(length=40), nullable=True),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "paid_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.String(length=1000), nullable=True),
        sa.Column("creation_idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(source = 'sale' AND sale_id IS NOT NULL AND appointment_id IS NULL) OR "
            "(source = 'appointment' AND appointment_id IS NOT NULL AND sale_id IS NULL)",
            name=op.f("ck_customer_receivables_source_reference_consistent"),
        ),
        sa.CheckConstraint(
            "source <> 'sale' OR payment_method_id IS NOT NULL",
            name=op.f("ck_customer_receivables_sale_payment_snapshot_required"),
        ),
        sa.CheckConstraint(
            "(status = 'pending' AND paid_amount = 0 AND paid_at IS NULL AND "
            "cancelled_at IS NULL) OR "
            "(status = 'partial' AND paid_amount > 0 AND paid_amount < amount AND "
            "paid_at IS NULL AND cancelled_at IS NULL) OR "
            "(status = 'paid' AND paid_amount = amount AND paid_at IS NOT NULL AND "
            "cancelled_at IS NULL) OR "
            "(status = 'cancelled' AND paid_amount = 0 AND paid_at IS NULL AND "
            "cancelled_at IS NOT NULL)",
            name=op.f("ck_customer_receivables_status_amount_consistent"),
        ),
        sa.CheckConstraint(
            "source IN ('sale', 'appointment')", name=op.f("ck_customer_receivables_source_values")
        ),
        sa.CheckConstraint(
            "status <> 'cancelled' OR cancellation_reason IS NOT NULL",
            name=op.f("ck_customer_receivables_cancelled_reason_required"),
        ),
        sa.CheckConstraint(
            "(payment_method_id IS NULL AND payment_method_code IS NULL AND "
            "payment_method_name IS NULL AND payment_channel IS NULL AND "
            "settlement_policy IS NULL AND affects_cash_drawer IS NULL AND "
            "requires_evidence IS NULL) OR "
            "(payment_method_id IS NOT NULL AND payment_method_code IS NOT NULL AND "
            "payment_method_name IS NOT NULL AND payment_channel IS NOT NULL AND "
            "settlement_policy IS NOT NULL AND affects_cash_drawer IS NOT NULL AND "
            "requires_evidence IS NOT NULL)",
            name=op.f("ck_customer_receivables_payment_snapshot_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'partial', 'paid', 'cancelled')",
            name=op.f("ck_customer_receivables_status_values"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_customer_receivables_amount_positive")),
        sa.CheckConstraint(
            "char_length(creation_idempotency_key) >= 8",
            name=op.f("ck_customer_receivables_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(currency_code) = 3",
            name=op.f("ck_customer_receivables_currency_code_length"),
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64",
            name=op.f("ck_customer_receivables_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)",
            name=op.f("ck_customer_receivables_currency_code_uppercase"),
        ),
        sa.CheckConstraint(
            "paid_amount <= amount", name=op.f("ck_customer_receivables_paid_amount_within_amount")
        ),
        sa.CheckConstraint(
            "paid_amount >= 0", name=op.f("ck_customer_receivables_paid_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_customer_receivables_created_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_customer_receivables_updated_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "appointment_id"],
            ["appointments.workspace_id", "appointments.id"],
            name="fk_customer_receivables_workspace_appointment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_customer_receivables_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "customer_id"],
            ["customers.workspace_id", "customers.id"],
            name="fk_customer_receivables_workspace_customer",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "payment_method_id"],
            ["payment_methods.workspace_id", "payment_methods.id"],
            name="fk_customer_receivables_workspace_payment_method",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "sale_id"],
            ["sales.workspace_id", "sales.id"],
            name="fk_customer_receivables_workspace_sale",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_customer_receivables_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_receivables")),
        sa.UniqueConstraint(
            "workspace_id", "branch_id", "id", name="uq_customer_receivables_workspace_branch_id"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "creation_idempotency_key",
            name="uq_customer_receivables_workspace_idempotency",
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_customer_receivables_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "receivable_number", name="uq_customer_receivables_workspace_number"
        ),
    )
    op.create_index(
        "ix_customer_receivables_workspace_branch_status_due",
        "customer_receivables",
        ["workspace_id", "branch_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_customer_receivables_workspace_customer_status_due",
        "customer_receivables",
        ["workspace_id", "customer_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "uq_customer_receivables_workspace_appointment",
        "customer_receivables",
        ["workspace_id", "appointment_id"],
        unique=True,
        postgresql_where=sa.text("appointment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_customer_receivables_workspace_sale",
        "customer_receivables",
        ["workspace_id", "sale_id"],
        unique=True,
        postgresql_where=sa.text("sale_id IS NOT NULL"),
    )
    op.create_table(
        "sale_lines",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("item_name", sa.String(length=160), nullable=False),
        sa.Column("item_sku", sa.String(length=64), nullable=True),
        sa.Column("item_type", sa.String(length=24), nullable=False),
        sa.Column("unit_symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("list_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_cost_snapshot", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sale_lines_discount_amount_non_negative")
        ),
        sa.CheckConstraint("line_total >= 0", name=op.f("ck_sale_lines_line_total_non_negative")),
        sa.CheckConstraint("list_price >= 0", name=op.f("ck_sale_lines_list_price_non_negative")),
        sa.CheckConstraint("position >= 1", name=op.f("ck_sale_lines_position_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sale_lines_quantity_positive")),
        sa.CheckConstraint("tax_amount >= 0", name=op.f("ck_sale_lines_tax_amount_non_negative")),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_sale_lines_tax_rate_range")
        ),
        sa.CheckConstraint(
            "unit_cost_snapshot IS NULL OR unit_cost_snapshot >= 0",
            name=op.f("ck_sale_lines_unit_cost_snapshot_non_negative"),
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sale_lines_unit_price_non_negative")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["items.workspace_id", "items.id"],
            name="fk_sale_lines_workspace_item",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "sale_id"],
            ["sales.workspace_id", "sales.id"],
            name="fk_sale_lines_workspace_sale",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sale_lines_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_sale_lines_workspace_id"),
        sa.UniqueConstraint("workspace_id", "sale_id", "position", name="uq_sale_lines_position"),
    )
    op.create_index(
        "ix_sale_lines_workspace_item", "sale_lines", ["workspace_id", "item_id"], unique=False
    )
    op.create_index(
        "ix_sale_lines_workspace_sale", "sale_lines", ["workspace_id", "sale_id"], unique=False
    )
    op.create_table(
        "customer_payments",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=False),
        sa.Column("cash_register_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'posted'"), nullable=False
        ),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_method_code", sa.String(length=48), nullable=False),
        sa.Column("payment_method_name", sa.String(length=120), nullable=False),
        sa.Column("payment_channel", sa.String(length=24), nullable=False),
        sa.Column("settlement_policy", sa.String(length=24), nullable=False),
        sa.Column("affects_cash_drawer", sa.Boolean(), nullable=False),
        sa.Column("requires_evidence", sa.Boolean(), nullable=False),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("received_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("received_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("received_by_name", sa.String(length=200), nullable=False),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_platform_user_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_reason", sa.String(length=1000), nullable=True),
        sa.Column("reversal_idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("reversal_request_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "(status = 'posted' AND reversed_at IS NULL AND "
            "reversed_by_platform_user_id IS NULL AND reversal_reason IS NULL) OR "
            "(status = 'reversed' AND reversed_at IS NOT NULL AND "
            "reversed_by_platform_user_id IS NOT NULL AND reversal_reason IS NOT NULL)",
            name=op.f("ck_customer_payments_reversal_state_consistent"),
        ),
        sa.CheckConstraint(
            "status IN ('posted', 'reversed')", name=op.f("ck_customer_payments_status_values")
        ),
        sa.CheckConstraint(
            "(reversal_idempotency_key IS NULL) = (reversal_request_fingerprint IS NULL)",
            name=op.f("ck_customer_payments_reversal_idempotency_pair"),
        ),
        sa.CheckConstraint(
            "NOT affects_cash_drawer OR cash_register_id IS NOT NULL",
            name=op.f("ck_customer_payments_cash_payment_requires_register"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_customer_payments_amount_positive")),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name=op.f("ck_customer_payments_currency_code_length")
        ),
        sa.CheckConstraint(
            "char_length(idempotency_key) >= 8",
            name=op.f("ck_customer_payments_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64",
            name=op.f("ck_customer_payments_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)",
            name=op.f("ck_customer_payments_currency_code_uppercase"),
        ),
        sa.ForeignKeyConstraint(
            ["received_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_customer_payments_received_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_customer_payments_reversed_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "cash_register_id"],
            ["cash_registers.workspace_id", "cash_registers.branch_id", "cash_registers.id"],
            name="fk_customer_payments_workspace_register",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "receivable_id"],
            [
                "customer_receivables.workspace_id",
                "customer_receivables.branch_id",
                "customer_receivables.id",
            ],
            name="fk_customer_payments_workspace_receivable",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_customer_payments_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "payment_method_id"],
            ["payment_methods.workspace_id", "payment_methods.id"],
            name="fk_customer_payments_workspace_payment_method",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "received_by_membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_customer_payments_workspace_receiver_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_customer_payments_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_payments")),
        sa.UniqueConstraint(
            "workspace_id", "branch_id", "id", name="uq_customer_payments_workspace_branch_id"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_customer_payments_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_customer_payments_idempotency"
        ),
    )
    op.create_index(
        "ix_customer_payments_workspace_branch_posted",
        "customer_payments",
        ["workspace_id", "branch_id", "posted_at"],
        unique=False,
    )
    op.create_index(
        "ix_customer_payments_workspace_receivable_posted",
        "customer_payments",
        ["workspace_id", "receivable_id", "posted_at"],
        unique=False,
    )
    op.create_index(
        "uq_customer_payments_reversal_idempotency",
        "customer_payments",
        ["workspace_id", "reversal_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("reversal_idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "customer_receivable_lines",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("sale_line_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("item_name", sa.String(length=160), nullable=False),
        sa.Column("item_sku", sa.String(length=64), nullable=True),
        sa.Column("unit_symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_customer_receivable_lines_line_total_non_negative")
        ),
        sa.CheckConstraint(
            "position >= 1", name=op.f("ck_customer_receivable_lines_position_positive")
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_customer_receivable_lines_quantity_positive")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_customer_receivable_lines_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["items.workspace_id", "items.id"],
            name="fk_customer_receivable_lines_workspace_item",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "receivable_id"],
            ["customer_receivables.workspace_id", "customer_receivables.id"],
            name="fk_customer_receivable_lines_workspace_receivable",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "sale_line_id"],
            ["sale_lines.workspace_id", "sale_lines.id"],
            name="fk_customer_receivable_lines_workspace_sale_line",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_customer_receivable_lines_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_receivable_lines")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_customer_receivable_lines_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id",
            "receivable_id",
            "position",
            name="uq_customer_receivable_lines_position",
        ),
    )
    op.create_index(
        "ix_customer_receivable_lines_workspace_receivable",
        "customer_receivable_lines",
        ["workspace_id", "receivable_id"],
        unique=False,
    )
    op.create_table(
        "cash_movements",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("cash_register_id", sa.Uuid(), nullable=False),
        sa.Column("movement_type", sa.String(length=24), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("cash_delta", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("payment_method_id", sa.Uuid(), nullable=True),
        sa.Column("payment_method_code", sa.String(length=48), nullable=True),
        sa.Column("payment_method_name", sa.String(length=120), nullable=True),
        sa.Column("payment_channel", sa.String(length=24), nullable=True),
        sa.Column("settlement_policy", sa.String(length=24), nullable=True),
        sa.Column("affects_cash_drawer", sa.Boolean(), nullable=True),
        sa.Column("requires_evidence", sa.Boolean(), nullable=True),
        sa.Column("sale_id", sa.Uuid(), nullable=True),
        sa.Column("customer_payment_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_of_movement_id", sa.Uuid(), nullable=True),
        sa.Column("inventory_movement_id", sa.Uuid(), nullable=True),
        sa.Column("concept", sa.String(length=240), nullable=False),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("created_by_membership_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_name", sa.String(length=200), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "(movement_type = 'sale' AND sale_id IS NOT NULL AND "
            "customer_payment_id IS NULL AND reversal_of_movement_id IS NULL) OR "
            "(movement_type = 'receivable_payment' AND customer_payment_id IS NOT NULL "
            "AND sale_id IS NULL AND reversal_of_movement_id IS NULL) OR "
            "(movement_type IN ('income', 'expense') AND sale_id IS NULL AND "
            "customer_payment_id IS NULL AND reversal_of_movement_id IS NULL) OR "
            "(movement_type = 'reversal' AND reversal_of_movement_id IS NOT NULL "
            "AND sale_id IS NULL AND customer_payment_id IS NULL)",
            name=op.f("ck_cash_movements_source_reference_consistent"),
        ),
        sa.CheckConstraint(
            "(movement_type IN ('sale', 'receivable_payment') AND "
            "payment_method_id IS NOT NULL AND payment_method_code IS NOT NULL "
            "AND payment_method_name IS NOT NULL AND payment_channel IS NOT NULL "
            "AND settlement_policy IS NOT NULL AND affects_cash_drawer IS NOT NULL "
            "AND requires_evidence IS NOT NULL) OR "
            "(movement_type NOT IN ('sale', 'receivable_payment'))",
            name=op.f("ck_cash_movements_payment_snapshot_required"),
        ),
        sa.CheckConstraint(
            "(movement_type IN ('sale', 'receivable_payment', 'income') AND "
            "cash_delta > 0) OR (movement_type = 'expense' AND cash_delta < 0) OR "
            "movement_type = 'reversal'",
            name=op.f("ck_cash_movements_cash_delta_direction"),
        ),
        sa.CheckConstraint(
            "movement_type IN ('sale', 'receivable_payment', 'income', 'expense', 'reversal')",
            name=op.f("ck_cash_movements_movement_type_values"),
        ),
        sa.CheckConstraint(
            "amount = abs(cash_delta)", name=op.f("ck_cash_movements_amount_matches_cash_delta")
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_cash_movements_amount_positive")),
        sa.CheckConstraint("cash_delta <> 0", name=op.f("ck_cash_movements_cash_delta_non_zero")),
        sa.CheckConstraint(
            "char_length(currency_code) = 3", name=op.f("ck_cash_movements_currency_code_length")
        ),
        sa.CheckConstraint(
            "char_length(idempotency_key) >= 8",
            name=op.f("ck_cash_movements_idempotency_key_length"),
        ),
        sa.CheckConstraint(
            "char_length(request_fingerprint) = 64",
            name=op.f("ck_cash_movements_fingerprint_length"),
        ),
        sa.CheckConstraint(
            "currency_code = upper(currency_code)",
            name=op.f("ck_cash_movements_currency_code_uppercase"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_cash_movements_created_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "cash_register_id"],
            ["cash_registers.workspace_id", "cash_registers.branch_id", "cash_registers.id"],
            name="fk_cash_movements_workspace_register",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "customer_payment_id"],
            [
                "customer_payments.workspace_id",
                "customer_payments.branch_id",
                "customer_payments.id",
            ],
            name="fk_cash_movements_workspace_customer_payment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "sale_id"],
            ["sales.workspace_id", "sales.branch_id", "sales.id"],
            name="fk_cash_movements_workspace_sale",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_cash_movements_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "created_by_membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_cash_movements_workspace_creator_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "inventory_movement_id"],
            ["inventory_movements.workspace_id", "inventory_movements.id"],
            name="fk_cash_movements_workspace_inventory_movement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "payment_method_id"],
            ["payment_methods.workspace_id", "payment_methods.id"],
            name="fk_cash_movements_workspace_payment_method",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "reversal_of_movement_id"],
            ["cash_movements.workspace_id", "cash_movements.id"],
            name="fk_cash_movements_workspace_reversal_of",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_cash_movements_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_cash_movements_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "idempotency_key", name="uq_cash_movements_idempotency"
        ),
    )
    op.create_index(
        "ix_cash_movements_workspace_branch_type_created",
        "cash_movements",
        ["workspace_id", "branch_id", "movement_type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_cash_movements_workspace_register_created",
        "cash_movements",
        ["workspace_id", "cash_register_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_cash_movements_workspace_customer_payment",
        "cash_movements",
        ["workspace_id", "customer_payment_id"],
        unique=True,
        postgresql_where=sa.text("customer_payment_id IS NOT NULL"),
    )
    op.create_index(
        "uq_cash_movements_workspace_reversal_of",
        "cash_movements",
        ["workspace_id", "reversal_of_movement_id"],
        unique=True,
        postgresql_where=sa.text("reversal_of_movement_id IS NOT NULL"),
    )
    op.create_index(
        "uq_cash_movements_workspace_sale",
        "cash_movements",
        ["workspace_id", "sale_id"],
        unique=True,
        postgresql_where=sa.text("sale_id IS NOT NULL"),
    )
    op.create_table(
        "payment_proofs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("receivable_id", sa.Uuid(), nullable=True),
        sa.Column("customer_payment_id", sa.Uuid(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')",
            name=op.f("ck_payment_proofs_content_type_values"),
        ),
        sa.CheckConstraint(
            "(receivable_id IS NOT NULL AND customer_payment_id IS NULL) OR "
            "(receivable_id IS NULL AND customer_payment_id IS NOT NULL)",
            name=op.f("ck_payment_proofs_single_owner"),
        ),
        sa.CheckConstraint(
            "char_length(checksum_sha256) = 64", name=op.f("ck_payment_proofs_checksum_length")
        ),
        sa.CheckConstraint(
            "size_bytes > 0 AND size_bytes <= 10485760",
            name=op.f("ck_payment_proofs_size_bytes_range"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_payment_proofs_uploaded_by_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "customer_payment_id"],
            [
                "customer_payments.workspace_id",
                "customer_payments.branch_id",
                "customer_payments.id",
            ],
            name="fk_payment_proofs_workspace_payment",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id", "receivable_id"],
            [
                "customer_receivables.workspace_id",
                "customer_receivables.branch_id",
                "customer_receivables.id",
            ],
            name="fk_payment_proofs_workspace_receivable",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "branch_id"],
            ["branches.workspace_id", "branches.id"],
            name="fk_payment_proofs_workspace_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_payment_proofs_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_proofs")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_payment_proofs_workspace_id"),
        sa.UniqueConstraint("workspace_id", "storage_key", name="uq_payment_proofs_storage_key"),
    )
    op.create_index(
        "ix_payment_proofs_workspace_payment",
        "payment_proofs",
        ["workspace_id", "customer_payment_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_proofs_workspace_receivable",
        "payment_proofs",
        ["workspace_id", "receivable_id"],
        unique=False,
    )
    op.create_index(
        "uq_payment_proofs_receivable_checksum",
        "payment_proofs",
        ["workspace_id", "receivable_id", "checksum_sha256"],
        unique=True,
        postgresql_where=sa.text("receivable_id IS NOT NULL"),
    )
    op.create_table(
        "cash_movement_lines",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("cash_movement_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=True),
        sa.Column("item_name", sa.String(length=160), nullable=False),
        sa.Column("item_sku", sa.String(length=64), nullable=True),
        sa.Column("unit_symbol", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("line_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "line_total >= 0", name=op.f("ck_cash_movement_lines_line_total_non_negative")
        ),
        sa.CheckConstraint("position >= 1", name=op.f("ck_cash_movement_lines_position_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_cash_movement_lines_quantity_positive")),
        sa.CheckConstraint(
            "unit_amount >= 0", name=op.f("ck_cash_movement_lines_unit_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "cash_movement_id"],
            ["cash_movements.workspace_id", "cash_movements.id"],
            name="fk_cash_movement_lines_workspace_movement",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "item_id"],
            ["items.workspace_id", "items.id"],
            name="fk_cash_movement_lines_workspace_item",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_cash_movement_lines_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movement_lines")),
        sa.UniqueConstraint(
            "workspace_id", "cash_movement_id", "position", name="uq_cash_movement_lines_position"
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_cash_movement_lines_workspace_id"),
    )
    op.create_index(
        "ix_cash_movement_lines_workspace_movement",
        "cash_movement_lines",
        ["workspace_id", "cash_movement_id"],
        unique=False,
    )
    op.add_column(
        "payment_methods",
        sa.Column(
            "channel", sa.String(length=24), server_default=sa.text("'other'"), nullable=False
        ),
    )
    op.add_column(
        "payment_methods",
        sa.Column(
            "settlement_policy",
            sa.String(length=24),
            server_default=sa.text("'immediate'"),
            nullable=False,
        ),
    )
    op.add_column(
        "payment_methods",
        sa.Column(
            "affects_cash_drawer", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "payment_methods",
        sa.Column(
            "requires_evidence", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_check_constraint(
        op.f("ck_payment_methods_cash_drawer_requires_cash_channel"),
        "payment_methods",
        "NOT affects_cash_drawer OR channel = 'cash'",
    )
    op.create_check_constraint(
        op.f("ck_payment_methods_channel_values"),
        "payment_methods",
        "channel IN ('cash', 'card', 'bank_transfer', 'payment_link', 'credit', 'other')",
    )
    op.create_check_constraint(
        op.f("ck_payment_methods_settlement_policy_values"),
        "payment_methods",
        "settlement_policy IN ('immediate', 'pending_confirmation', 'receivable')",
    )
    _install_terminal_pos_catalogs()
    _backfill_appointment_receivables()


def _backfill_appointment_receivables() -> None:
    """Create opening CxC records only for attributable legacy appointment debt.

    ``pending_amount`` is the only legacy balance available, so it becomes the original
    amount with no inferred payment history. Appointments without a registered customer
    are deliberately excluded: assigning their debt to a guessed customer would corrupt
    the financial ledger.
    """
    op.execute(
        """
        WITH eligible AS (
            SELECT
                appointment.*,
                workspace.default_currency,
                counter.last_receivable_value
                    + row_number() OVER (
                        PARTITION BY appointment.workspace_id
                        ORDER BY appointment.created_at, appointment.id
                    ) AS document_value
            FROM appointments AS appointment
            JOIN workspaces AS workspace
              ON workspace.id = appointment.workspace_id
            JOIN sales_document_counters AS counter
              ON counter.workspace_id = appointment.workspace_id
            WHERE appointment.pending_payment IS TRUE
              AND appointment.pending_amount > 0
              AND appointment.status <> 'cancelled'
              AND appointment.customer_id IS NOT NULL
              AND NOT EXISTS (
                    SELECT 1
                    FROM customer_receivables AS existing
                    WHERE existing.workspace_id = appointment.workspace_id
                      AND existing.appointment_id = appointment.id
              )
        )
        INSERT INTO customer_receivables (
            workspace_id,
            branch_id,
            customer_id,
            receivable_number,
            source,
            sale_id,
            appointment_id,
            payment_method_id,
            payment_method_code,
            payment_method_name,
            payment_channel,
            settlement_policy,
            affects_cash_drawer,
            requires_evidence,
            currency_code,
            customer_name,
            customer_phone,
            amount,
            paid_amount,
            status,
            reference,
            notes,
            due_date,
            paid_at,
            cancelled_at,
            cancellation_reason,
            creation_idempotency_key,
            request_fingerprint,
            created_by_platform_user_id,
            updated_by_platform_user_id,
            created_at,
            updated_at,
            version
        )
        SELECT
            eligible.workspace_id,
            eligible.branch_id,
            eligible.customer_id,
            'CXC-' || CASE
                WHEN length(eligible.document_value::text) < 8
                    THEN lpad(eligible.document_value::text, 8, '0')
                ELSE eligible.document_value::text
            END,
            'appointment',
            NULL,
            eligible.id,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            upper(eligible.default_currency),
            eligible.customer_name,
            eligible.customer_phone,
            eligible.pending_amount,
            0,
            'pending',
            'Cita ' || eligible.scheduled_date::text || ' '
                || to_char(eligible.scheduled_time, 'HH24:MI'),
            'Servicio: ' || left(eligible.service_name, 989),
            eligible.scheduled_date,
            NULL,
            NULL,
            NULL,
            'agenda-backfill:' || eligible.id::text,
            eligible.request_fingerprint,
            eligible.created_by_platform_user_id,
            eligible.updated_by_platform_user_id,
            eligible.created_at,
            eligible.updated_at,
            1
        FROM eligible
        ON CONFLICT (workspace_id, appointment_id)
            WHERE appointment_id IS NOT NULL
            DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO customer_receivable_lines (
            workspace_id,
            receivable_id,
            position,
            sale_line_id,
            item_id,
            item_name,
            item_sku,
            unit_symbol,
            quantity,
            unit_price,
            line_total
        )
        SELECT
            receivable.workspace_id,
            receivable.id,
            1,
            NULL,
            appointment.service_id,
            left(
                coalesce(nullif(btrim(appointment.service_name), ''), 'Servicio de cita'),
                160
            ),
            NULL,
            'serv',
            1.000,
            receivable.amount,
            receivable.amount
        FROM customer_receivables AS receivable
        JOIN appointments AS appointment
          ON appointment.workspace_id = receivable.workspace_id
         AND appointment.id = receivable.appointment_id
        WHERE receivable.source = 'appointment'
        ON CONFLICT (workspace_id, receivable_id, position) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE sales_document_counters AS counter
        SET last_receivable_value = greatest(
                counter.last_receivable_value,
                numbered.last_receivable_value
            ),
            updated_at = now()
        FROM (
            SELECT
                workspace_id,
                max(substring(receivable_number FROM 5)::integer) AS last_receivable_value
            FROM customer_receivables
            WHERE receivable_number ~ '^CXC-[0-9]+$'
            GROUP BY workspace_id
        ) AS numbered
        WHERE numbered.workspace_id = counter.workspace_id
        """
    )


def _install_terminal_pos_catalogs() -> None:
    op.execute(
        """
        INSERT INTO sales_document_counters
            (workspace_id, last_quote_value, last_sale_value, last_receivable_value)
        SELECT id, 0, 0, 0
        FROM workspaces
        ON CONFLICT (workspace_id) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE payment_methods
        SET channel = CASE code
                WHEN 'cash' THEN 'cash'
                WHEN 'card' THEN 'card'
                WHEN 'transfer' THEN 'bank_transfer'
                WHEN 'bank_transfer' THEN 'bank_transfer'
                WHEN 'payment_link' THEN 'payment_link'
                WHEN 'credit' THEN 'credit'
                ELSE channel
            END,
            settlement_policy = CASE code
                WHEN 'transfer' THEN 'pending_confirmation'
                WHEN 'bank_transfer' THEN 'pending_confirmation'
                WHEN 'payment_link' THEN 'pending_confirmation'
                WHEN 'credit' THEN 'receivable'
                ELSE settlement_policy
            END,
            affects_cash_drawer = code = 'cash',
            requires_evidence = code IN ('transfer', 'bank_transfer', 'payment_link'),
            updated_at = now()
        WHERE code IN (
            'cash', 'card', 'transfer', 'bank_transfer', 'payment_link', 'credit'
        )
        """
    )
    op.execute(
        """
        INSERT INTO payment_methods
            (workspace_id, code, name, icon, status, is_system, channel,
             settlement_policy, affects_cash_drawer, requires_evidence)
        SELECT workspace.id, method.code, method.name, method.icon, 'active', true,
               method.channel, method.settlement_policy,
               method.affects_cash_drawer, method.requires_evidence
        FROM workspaces AS workspace
        CROSS JOIN (
            VALUES
                ('cash', 'Efectivo', 'Banknote', 'cash', 'immediate', true, false),
                ('card', 'Tarjeta', 'CreditCard', 'card', 'immediate', false, false),
                ('transfer', 'Transferencia', 'Landmark', 'bank_transfer',
                 'pending_confirmation', false, true),
                ('payment_link', 'Link de pago', 'Link2', 'payment_link',
                 'pending_confirmation', false, true),
                ('credit', 'Cuenta por cobrar', 'Clock', 'credit',
                 'receivable', false, false)
        ) AS method(
            code, name, icon, channel, settlement_policy,
            affects_cash_drawer, requires_evidence
        )
        ON CONFLICT (workspace_id, code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO module_definitions (code, name, kind, status, dependency_codes)
        VALUES
            ('sales', 'Sales', 'optional', 'available', '["crm", "catalog"]'),
            ('pos', 'Point of sale', 'optional', 'available', '["sales", "inventory"]')
        ON CONFLICT (code) DO UPDATE SET
            name = EXCLUDED.name,
            kind = EXCLUDED.kind,
            status = EXCLUDED.status,
            dependency_codes = EXCLUDED.dependency_codes,
            updated_at = now()
        """
    )
    op.execute(
        """
        INSERT INTO permissions
            (code, module_code, action, name, description, sort_order, is_platform_only)
        VALUES
            ('sales.read', 'sales', 'read', 'Ver ventas',
             'View posted sales and their immutable commercial snapshots.', 10, false),
            ('sales.quote.manage', 'sales', 'quote.manage', 'Gestionar cotizaciones',
             'Create, update, cancel, expire, and convert quotes or held carts.', 20, false),
            ('pos.read', 'pos', 'read', 'Ver Terminal POS',
             'View the POS catalog, register state, and recent operations.', 10, false),
            ('pos.sell', 'pos', 'sell', 'Registrar ventas',
             'Post idempotent sales in an authorized branch.', 20, false),
            ('pos.discount.override', 'pos', 'discount.override', 'Autorizar descuentos',
             'Override standard discounts while posting a sale.', 30, false),
            ('pos.register.manage', 'pos', 'register.manage', 'Gestionar turnos de caja',
             'Open and close branch cash-register sessions.', 40, false),
            ('pos.cash.read', 'pos', 'cash.read', 'Ver movimientos de caja',
             'View branch cash-register sessions and drawer movements.', 50, false),
            ('pos.cash.manage', 'pos', 'cash.manage', 'Gestionar movimientos de caja',
             'Register idempotent cash income, expenses, and reversals.', 60, false),
            ('pos.receivables.read', 'pos', 'receivables.read', 'Ver cuentas por cobrar',
             'View customer balances, payment history, and evidence.', 70, false),
            ('pos.receivables.collect', 'pos', 'receivables.collect', 'Cobrar cuentas',
             'Post and reverse customer receivable payments.', 80, false),
            ('pos.receivables.manage', 'pos', 'receivables.manage',
             'Gestionar cuentas por cobrar',
             'Create, cancel, and administer customer receivables.', 90, false),
            ('pos.void', 'pos', 'void', 'Anular ventas',
             'Void posted sales and record their compensating movements.', 100, false)
        ON CONFLICT (code) DO UPDATE SET
            module_code = EXCLUDED.module_code,
            action = EXCLUDED.action,
            name = EXCLUDED.name,
            description = EXCLUDED.description,
            sort_order = EXCLUDED.sort_order,
            is_platform_only = EXCLUDED.is_platform_only,
            updated_at = now()
        """
    )
    for role_code, permission_codes in _ROLE_PERMISSION_CODES.items():
        permission_sql = ", ".join(f"'{code}'" for code in permission_codes)
        op.execute(
            sa.text(
                f"""
                INSERT INTO role_permissions (workspace_id, role_id, permission_id)
                SELECT role.workspace_id, role.id, permission.id
                FROM roles AS role
                CROSS JOIN permissions AS permission
                WHERE role.code = :role_code
                  AND role.status = 'active'
                  AND permission.code IN ({permission_sql})
                ON CONFLICT (workspace_id, role_id, permission_id) DO NOTHING
                """
            ).bindparams(role_code=role_code)
        )
    op.execute(
        """
        INSERT INTO module_entitlements
            (workspace_id, module_definition_id, status, effective_from)
        SELECT workspace.id, module.id, 'enabled', now()
        FROM workspaces AS workspace
        CROSS JOIN module_definitions AS module
        WHERE module.code IN ('sales', 'pos')
        ON CONFLICT (workspace_id, module_definition_id) DO NOTHING
        """
    )


def _remove_terminal_pos_catalogs() -> None:
    """Preserve shared IAM catalogs whose provenance predates this schema revision.

    The migration installs global permission/module rows and workspace entitlements with
    conflict-tolerant inserts, so it cannot distinguish rows it created from pre-existing
    configuration during downgrade. Keeping those catalogs is safer than deleting durable
    grants owned by an earlier deployment or a workspace administrator.
    """


def downgrade() -> None:
    """Downgrade schema."""
    _remove_terminal_pos_catalogs()
    op.drop_constraint(
        op.f("ck_payment_methods_settlement_policy_values"), "payment_methods", type_="check"
    )
    op.drop_constraint(op.f("ck_payment_methods_channel_values"), "payment_methods", type_="check")
    op.drop_constraint(
        op.f("ck_payment_methods_cash_drawer_requires_cash_channel"),
        "payment_methods",
        type_="check",
    )
    op.drop_column("payment_methods", "requires_evidence")
    op.drop_column("payment_methods", "affects_cash_drawer")
    op.drop_column("payment_methods", "settlement_policy")
    op.drop_column("payment_methods", "channel")
    op.drop_index("ix_cash_movement_lines_workspace_movement", table_name="cash_movement_lines")
    op.drop_table("cash_movement_lines")
    op.execute("DROP INDEX IF EXISTS uq_payment_proofs_receivable_checksum")
    op.drop_index("ix_payment_proofs_workspace_receivable", table_name="payment_proofs")
    op.drop_index("ix_payment_proofs_workspace_payment", table_name="payment_proofs")
    op.drop_table("payment_proofs")
    op.drop_index(
        "uq_cash_movements_workspace_sale",
        table_name="cash_movements",
        postgresql_where=sa.text("sale_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_cash_movements_workspace_reversal_of",
        table_name="cash_movements",
        postgresql_where=sa.text("reversal_of_movement_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_cash_movements_workspace_customer_payment",
        table_name="cash_movements",
        postgresql_where=sa.text("customer_payment_id IS NOT NULL"),
    )
    op.drop_index("ix_cash_movements_workspace_register_created", table_name="cash_movements")
    op.drop_index("ix_cash_movements_workspace_branch_type_created", table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(
        "ix_customer_receivable_lines_workspace_receivable", table_name="customer_receivable_lines"
    )
    op.drop_table("customer_receivable_lines")
    op.drop_index(
        "uq_customer_payments_reversal_idempotency",
        table_name="customer_payments",
        postgresql_where=sa.text("reversal_idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "ix_customer_payments_workspace_receivable_posted", table_name="customer_payments"
    )
    op.drop_index("ix_customer_payments_workspace_branch_posted", table_name="customer_payments")
    op.drop_table("customer_payments")
    op.drop_index("ix_sale_lines_workspace_sale", table_name="sale_lines")
    op.drop_index("ix_sale_lines_workspace_item", table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(
        "uq_customer_receivables_workspace_sale",
        table_name="customer_receivables",
        postgresql_where=sa.text("sale_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_customer_receivables_workspace_appointment",
        table_name="customer_receivables",
        postgresql_where=sa.text("appointment_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_customer_receivables_workspace_customer_status_due", table_name="customer_receivables"
    )
    op.drop_index(
        "ix_customer_receivables_workspace_branch_status_due", table_name="customer_receivables"
    )
    op.drop_table("customer_receivables")
    op.drop_index(
        "uq_sales_workspace_void_idempotency",
        table_name="sales",
        postgresql_where=sa.text("void_idempotency_key IS NOT NULL"),
    )
    op.drop_index(
        "uq_sales_workspace_quote",
        table_name="sales",
        postgresql_where=sa.text("quote_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_sales_workspace_inventory_movement",
        table_name="sales",
        postgresql_where=sa.text("inventory_movement_id IS NOT NULL"),
    )
    op.drop_index("ix_sales_workspace_customer_completed", table_name="sales")
    op.drop_index("ix_sales_workspace_branch_completed", table_name="sales")
    op.drop_table("sales")
    op.drop_index("ix_sales_quote_lines_workspace_quote", table_name="sales_quote_lines")
    op.drop_index("ix_sales_quote_lines_workspace_item", table_name="sales_quote_lines")
    op.drop_table("sales_quote_lines")
    op.drop_index("ix_sales_quotes_workspace_customer_status", table_name="sales_quotes")
    op.drop_index("ix_sales_quotes_workspace_branch_status_updated", table_name="sales_quotes")
    op.drop_table("sales_quotes")
    op.drop_index(
        "uq_cash_registers_open_branch",
        table_name="cash_registers",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index(
        "uq_cash_registers_close_idempotency",
        table_name="cash_registers",
        postgresql_where=sa.text("close_idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_cash_registers_workspace_branch_opened", table_name="cash_registers")
    op.drop_table("cash_registers")
    op.drop_table("sales_document_counters")
    # ### end Alembic commands ###
