"""create foundation schema

Revision ID: 4a983691d307
Revises: 20260820_0001
Create Date: 2026-08-21 07:56:36.416551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4a983691d307"
down_revision: str | Sequence[str] | None = "20260820_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_definitions",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "dependency_codes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('core', 'optional')", name=op.f("ck_module_definitions_kind_values")
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'available', 'deprecated')",
            name=op.f("ck_module_definitions_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_module_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_module_definitions_code")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=96), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column(
            "is_platform_only", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "platform_users",
        sa.Column("external_subject", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_platform_users_status_values")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_users")),
        sa.UniqueConstraint("email", name=op.f("uq_platform_users_email")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_platform_users_external_subject")),
    )
    op.create_table(
        "regional_packs",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('planned', 'available', 'deprecated')",
            name=op.f("ck_regional_packs_status_values"),
        ),
        sa.CheckConstraint(
            "char_length(jurisdiction_code) = 2", name=op.f("ck_regional_packs_jurisdiction_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regional_packs")),
        sa.UniqueConstraint("code", name=op.f("uq_regional_packs_code")),
    )
    op.create_table(
        "workspaces",
        sa.Column("slug", sa.String(length=63), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default=sa.text("'onboarding'"), nullable=False
        ),
        sa.Column("default_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('onboarding', 'active', 'suspended', 'closing', 'closed')",
            name=op.f("ck_workspaces_status_values"),
        ),
        sa.CheckConstraint(
            "char_length(default_currency) = 3", name=op.f("ck_workspaces_currency_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("slug", name=op.f("uq_workspaces_slug")),
    )
    op.create_table(
        "audit_entries",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("actor_platform_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('success', 'denied', 'failure')",
            name=op.f("ck_audit_entries_outcome_values"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_audit_entries_actor_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_audit_entries_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_entries")),
    )
    op.create_index(
        "ix_audit_entries_actor", "audit_entries", ["actor_platform_user_id"], unique=False
    )
    op.create_index("ix_audit_entries_request", "audit_entries", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_entries_target", "audit_entries", ["target_type", "target_id"], unique=False
    )
    op.create_index(
        "ix_audit_entries_workspace_occurred",
        "audit_entries",
        ["workspace_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "legal_entities",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("legal_name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=True),
        sa.Column(
            "status", sa.String(length=24), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'archived')",
            name=op.f("ck_legal_entities_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_legal_entities_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entities")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_legal_entities_workspace_code"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_legal_entities_workspace_id_id"),
    )
    op.create_index(
        "ix_legal_entities_workspace_status",
        "legal_entities",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "module_entitlements",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("module_definition_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('enabled', 'disabled', 'suspended')",
            name=op.f("ck_module_entitlements_status_values"),
        ),
        sa.CheckConstraint(
            "effective_until IS NULL OR effective_until >= effective_from",
            name=op.f("ck_module_entitlements_effective_period"),
        ),
        sa.ForeignKeyConstraint(
            ["module_definition_id"],
            ["module_definitions.id"],
            name=op.f("fk_module_entitlements_module_definition_id_module_definitions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_module_entitlements_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_module_entitlements")),
        sa.UniqueConstraint(
            "workspace_id", "module_definition_id", name="uq_entitlements_workspace_module"
        ),
    )
    op.create_index(
        "ix_entitlements_module", "module_entitlements", ["module_definition_id"], unique=False
    )
    op.create_index(
        "ix_entitlements_workspace_status",
        "module_entitlements",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "regional_rule_versions",
        sa.Column("regional_pack_id", sa.Uuid(), nullable=False),
        sa.Column("rule_type", sa.String(length=48), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'retired')",
            name=op.f("ck_regional_rule_versions_status_values"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_regional_rule_versions_period"),
        ),
        sa.ForeignKeyConstraint(
            ["regional_pack_id"],
            ["regional_packs.id"],
            name=op.f("fk_regional_rule_versions_regional_pack_id_regional_packs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regional_rule_versions")),
        sa.UniqueConstraint(
            "regional_pack_id",
            "rule_type",
            "version_number",
            name="uq_regional_rules_pack_type_version",
        ),
    )
    op.create_index(
        "ix_regional_rules_pack_type_status",
        "regional_rule_versions",
        ["regional_pack_id", "rule_type", "status"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_roles_status_values")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_roles_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_roles_workspace_code"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_roles_workspace_id_id"),
    )
    op.create_index("ix_roles_workspace_status", "roles", ["workspace_id", "status"], unique=False)
    op.create_table(
        "workspace_memberships",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("platform_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'suspended', 'revoked', 'expired')",
            name=op.f("ck_workspace_memberships_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_workspace_memberships_platform_user_id_platform_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_memberships")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_memberships_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "platform_user_id", name="uq_memberships_workspace_user"
        ),
    )
    op.create_index(
        "ix_memberships_platform_user", "workspace_memberships", ["platform_user_id"], unique=False
    )
    op.create_index(
        "ix_memberships_workspace_status",
        "workspace_memberships",
        ["workspace_id", "status"],
        unique=False,
    )
    op.create_table(
        "branches",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "status", sa.String(length=24), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'archived')", name=op.f("ck_branches_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "legal_entity_id"],
            ["legal_entities.workspace_id", "legal_entities.id"],
            name="fk_branches_workspace_entity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_branches")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_branches_workspace_code"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_branches_workspace_id_id"),
        sa.UniqueConstraint(
            "workspace_id", "legal_entity_id", "id", name="uq_branches_workspace_entity_id"
        ),
    )
    op.create_index(
        "ix_branches_workspace_entity",
        "branches",
        ["workspace_id", "legal_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_branches_workspace_status", "branches", ["workspace_id", "status"], unique=False
    )
    op.create_table(
        "legal_entity_identities",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("registered_name", sa.String(length=200), nullable=False),
        sa.Column("jurisdiction_code", sa.String(length=2), nullable=False),
        sa.Column("identifier_type", sa.String(length=32), nullable=True),
        sa.Column("identifier_value", sa.String(length=80), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(identifier_type IS NULL) = (identifier_value IS NULL)",
            name=op.f("ck_legal_entity_identities_identifier_pair"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_legal_entity_identities_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "legal_entity_id"],
            ["legal_entities.workspace_id", "legal_entities.id"],
            name="fk_entity_identities_workspace_entity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entity_identities")),
    )
    op.create_index(
        "ix_entity_identities_workspace_entity",
        "legal_entity_identities",
        ["workspace_id", "legal_entity_id"],
        unique=False,
    )
    op.create_table(
        "legal_entity_regional_rules",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=False),
        sa.Column("regional_rule_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'retired')",
            name=op.f("ck_legal_entity_regional_rules_status_values"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_legal_entity_regional_rules_period"),
        ),
        sa.ForeignKeyConstraint(
            ["regional_rule_version_id"],
            ["regional_rule_versions.id"],
            name=op.f(
                "fk_legal_entity_regional_rules_regional_rule_version_id_regional_rule_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "legal_entity_id"],
            ["legal_entities.workspace_id", "legal_entities.id"],
            name="fk_entity_regional_rules_workspace_entity",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_entity_regional_rules")),
    )
    op.create_index(
        "ix_entity_regional_rules_rule",
        "legal_entity_regional_rules",
        ["regional_rule_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_entity_regional_rules_workspace_entity",
        "legal_entity_regional_rules",
        ["workspace_id", "legal_entity_id", "status"],
        unique=False,
    )
    op.create_table(
        "role_permissions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "role_id"],
            ["roles.workspace_id", "roles.id"],
            name="fk_role_permissions_workspace_role",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint(
            "workspace_id", "role_id", "permission_id", name="uq_role_permissions_role_permission"
        ),
    )
    op.create_index(
        "ix_role_permissions_permission", "role_permissions", ["permission_id"], unique=False
    )
    op.create_index(
        "ix_role_permissions_workspace_role",
        "role_permissions",
        ["workspace_id", "role_id"],
        unique=False,
    )
    op.create_table(
        "access_scopes",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=24), nullable=False),
        sa.Column("legal_entity_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'workspace' AND legal_entity_id IS NULL AND branch_id IS NULL) OR "
            "(scope_type = 'legal_entity' AND legal_entity_id IS NOT NULL "
            "AND branch_id IS NULL) OR "
            "(scope_type = 'branch' AND legal_entity_id IS NOT NULL AND branch_id IS NOT NULL)",
            name=op.f("ck_access_scopes_target_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "legal_entity_id", "branch_id"],
            ["branches.workspace_id", "branches.legal_entity_id", "branches.id"],
            name="fk_access_scopes_workspace_entity_branch",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "legal_entity_id"],
            ["legal_entities.workspace_id", "legal_entities.id"],
            name="fk_access_scopes_workspace_entity",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_access_scopes_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_scopes")),
        sa.UniqueConstraint("workspace_id", "id", name="uq_access_scopes_workspace_id_id"),
    )
    op.create_index(
        "ix_access_scopes_workspace_entity",
        "access_scopes",
        ["workspace_id", "legal_entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_access_scopes_workspace_entity_branch",
        "access_scopes",
        ["workspace_id", "legal_entity_id", "branch_id"],
        unique=False,
    )
    op.create_index(
        "uq_access_scopes_branch",
        "access_scopes",
        ["workspace_id", "branch_id"],
        unique=True,
        postgresql_where=sa.text("scope_type = 'branch'"),
    )
    op.create_index(
        "uq_access_scopes_legal_entity",
        "access_scopes",
        ["workspace_id", "legal_entity_id"],
        unique=True,
        postgresql_where=sa.text("scope_type = 'legal_entity'"),
    )
    op.create_index(
        "uq_access_scopes_workspace",
        "access_scopes",
        ["workspace_id"],
        unique=True,
        postgresql_where=sa.text("scope_type = 'workspace'"),
    )
    op.create_table(
        "role_assignments",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("membership_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("access_scope_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')",
            name=op.f("ck_role_assignments_status_values"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until >= valid_from",
            name=op.f("ck_role_assignments_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "access_scope_id"],
            ["access_scopes.workspace_id", "access_scopes.id"],
            name="fk_role_assignments_workspace_scope",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "membership_id"],
            ["workspace_memberships.workspace_id", "workspace_memberships.id"],
            name="fk_role_assignments_workspace_membership",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "role_id"],
            ["roles.workspace_id", "roles.id"],
            name="fk_role_assignments_workspace_role",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_role_assignments_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
    )
    op.create_index(
        "ix_role_assignments_workspace_member",
        "role_assignments",
        ["workspace_id", "membership_id"],
        unique=False,
    )
    op.create_index(
        "ix_role_assignments_workspace_scope",
        "role_assignments",
        ["workspace_id", "access_scope_id"],
        unique=False,
    )
    op.create_index(
        "uq_role_assignments_active",
        "role_assignments",
        ["workspace_id", "membership_id", "role_id", "access_scope_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_role_assignments_active",
        table_name="role_assignments",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_role_assignments_workspace_scope", table_name="role_assignments")
    op.drop_index("ix_role_assignments_workspace_member", table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index(
        "uq_access_scopes_workspace",
        table_name="access_scopes",
        postgresql_where=sa.text("scope_type = 'workspace'"),
    )
    op.drop_index(
        "uq_access_scopes_legal_entity",
        table_name="access_scopes",
        postgresql_where=sa.text("scope_type = 'legal_entity'"),
    )
    op.drop_index(
        "uq_access_scopes_branch",
        table_name="access_scopes",
        postgresql_where=sa.text("scope_type = 'branch'"),
    )
    op.drop_index("ix_access_scopes_workspace_entity_branch", table_name="access_scopes")
    op.drop_index("ix_access_scopes_workspace_entity", table_name="access_scopes")
    op.drop_table("access_scopes")
    op.drop_index("ix_role_permissions_workspace_role", table_name="role_permissions")
    op.drop_index("ix_role_permissions_permission", table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(
        "ix_entity_regional_rules_workspace_entity", table_name="legal_entity_regional_rules"
    )
    op.drop_index("ix_entity_regional_rules_rule", table_name="legal_entity_regional_rules")
    op.drop_table("legal_entity_regional_rules")
    op.drop_index("ix_entity_identities_workspace_entity", table_name="legal_entity_identities")
    op.drop_table("legal_entity_identities")
    op.drop_index("ix_branches_workspace_status", table_name="branches")
    op.drop_index("ix_branches_workspace_entity", table_name="branches")
    op.drop_table("branches")
    op.drop_index("ix_memberships_workspace_status", table_name="workspace_memberships")
    op.drop_index("ix_memberships_platform_user", table_name="workspace_memberships")
    op.drop_table("workspace_memberships")
    op.drop_index("ix_roles_workspace_status", table_name="roles")
    op.drop_table("roles")
    op.drop_index("ix_regional_rules_pack_type_status", table_name="regional_rule_versions")
    op.drop_table("regional_rule_versions")
    op.drop_index("ix_entitlements_workspace_status", table_name="module_entitlements")
    op.drop_index("ix_entitlements_module", table_name="module_entitlements")
    op.drop_table("module_entitlements")
    op.drop_index("ix_legal_entities_workspace_status", table_name="legal_entities")
    op.drop_table("legal_entities")
    op.drop_index("ix_audit_entries_workspace_occurred", table_name="audit_entries")
    op.drop_index("ix_audit_entries_target", table_name="audit_entries")
    op.drop_index("ix_audit_entries_request", table_name="audit_entries")
    op.drop_index("ix_audit_entries_actor", table_name="audit_entries")
    op.drop_table("audit_entries")
    op.drop_table("workspaces")
    op.drop_table("regional_packs")
    op.drop_table("platform_users")
    op.drop_table("permissions")
    op.drop_table("module_definitions")
    # ### end Alembic commands ###
