import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { currencyFormatter } from '../lib/settings'
import { CarwashPanel, CarwashEmpty, CarwashTable } from './CarwashPrimitives'

const COLORS = ['#2563eb', '#10b981', '#f59e0b', '#8b5cf6', '#06b6d4', '#ec4899', '#64748b', '#84cc16', '#f97316', '#94a3b8']
const SERIES = [['billed', 'Facturado', '#2563eb'], ['washerCommissions', 'Lavadores', '#10b981'], ['supervisorCommissions', 'Encargados', '#f59e0b']]
const shortDate = (value) => `${value.slice(8, 10)}/${value.slice(5, 7)}`

export function ReportCharts({ data, workspace }) {
  const money = currencyFormatter({ ...workspace, defaultCurrency: data.currency })
  const compactMoney = (value) => new Intl.NumberFormat(workspace?.locale || 'es', { notation: 'compact', maximumFractionDigits: 1 }).format(value)
  const chartRows = (rows) => rows.map((row) => ({ ...row, billed: Number(row.billed || 0), washerCommissions: Number(row.washerCommissions), supervisorCommissions: Number(row.supervisorCommissions) }))
  const daily = chartRows(data.daily)
  const employees = chartRows(data.employees).map((row) => ({ ...row, shortName: row.name.length > 16 ? `${row.name.slice(0, 15)}…` : row.name }))
  return <>
    <p className="text-xs text-slate-500" data-testid="carwash-report-period">Período: {data.dateFrom} al {data.dateTo} · {data.timezone}. Facturación con impuestos; comisiones devengadas, estén pagadas o pendientes. Anulaciones excluidas.</p>
    <div className="grid min-w-0 gap-5 xl:grid-cols-2">
      <CarwashPanel title="Historial de Ventas vs Comisiones" description="Facturado y comisiones por fecha de finalización del lavado.">
        <div className="mb-4 flex flex-wrap gap-x-6 gap-y-2 text-sm"><p>{data.totals.washes} lavados · <strong data-testid="carwash-report-billed">{money(data.totals.billed)}</strong> facturado</p><p><strong data-testid="carwash-report-commissions">{money(data.totals.commissions)}</strong> en comisiones</p></div>
        {data.totals.washes ? <div className="min-w-0" data-testid="carwash-report-lines"><ResponsiveContainer width="100%" height={280} minWidth={0}><LineChart data={daily} accessibilityLayer margin={{ top: 12, right: 12, left: -12, bottom: 8 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" /><XAxis dataKey="date" tickFormatter={shortDate} minTickGap={32} tick={{ fontSize: 11 }} /><YAxis tickFormatter={compactMoney} width={62} tick={{ fontSize: 11 }} /><Tooltip formatter={(value, name) => [money(value), name]} labelFormatter={(value) => `Fecha: ${value}`} /><Legend wrapperStyle={{ fontSize: 12 }} />{SERIES.map(([key, name, color]) => <Line key={key} type="linear" dataKey={key} name={name} stroke={color} strokeWidth={2} dot={data.daily.length <= 7} isAnimationActive={false} />)}</LineChart></ResponsiveContainer></div> : <CarwashEmpty message="No hay lavados completados en este período." />}
        <details className="mt-4 text-sm"><summary className="cursor-pointer font-medium text-slate-600">Ver detalle diario</summary><div className="mt-3 max-h-80 overflow-auto"><CarwashTable testId="carwash-report-daily" rows={data.daily.map((row) => ({ ...row, id: row.date }))} columns={[{ key: 'date', label: 'Fecha', render: (row) => row.date }, { key: 'washes', label: 'Lavados', render: (row) => row.washes }, ...SERIES.map(([key, label]) => ({ key, label, render: (row) => money(row[key]) }))]} emptyMessage="Sin registros." /></div></details>
      </CarwashPanel>
      <CarwashPanel title="Servicios más Solicitados" description="Servicios realizados en lavados completados, incluidos los gratuitos.">
        <p className="mb-2 text-sm text-slate-600">{data.totals.serviceCount} servicios · Los nueve más solicitados y el resto agrupado.</p>
        {data.services.length ? <><div data-testid="carwash-report-donut"><ResponsiveContainer width="100%" height={240} minWidth={0}><PieChart accessibilityLayer><Pie data={data.services} dataKey="count" nameKey="name" innerRadius={65} outerRadius={95} paddingAngle={2} isAnimationActive={false}>{data.services.map((row, index) => <Cell key={row.itemId || 'other'} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip formatter={(value) => [`${value} servicios`]} /></PieChart></ResponsiveContainer></div><ul className="space-y-2 text-sm" data-testid="carwash-report-services">{data.services.map((row, index) => <li key={row.itemId || 'other'} className="flex items-start justify-between gap-3"><span className="flex min-w-0 items-start gap-2"><span aria-hidden className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: COLORS[index % COLORS.length] }} /><span className="break-words">{row.name}</span></span><strong className="shrink-0">{row.count}</strong></li>)}</ul></> : <CarwashEmpty message="No hay servicios realizados en este período." />}
      </CarwashPanel>
    </div>
    <CarwashPanel title="Ranking de Empleados por Comisiones Totales" description={`Los ${Math.min(10, data.totals.employeeCount)} primeros de ${data.totals.employeeCount} empleados, sumando ambos roles sin duplicar lavados.`}>
      {employees.length ? <><div data-testid="carwash-report-ranking"><ResponsiveContainer width="100%" height={Math.max(180, employees.length * 48 + 65)} minWidth={0}><BarChart data={employees} layout="vertical" accessibilityLayer margin={{ top: 8, right: 16, left: 0, bottom: 8 }}><CartesianGrid stroke="#e2e8f0" strokeDasharray="3 3" horizontal={false} /><XAxis type="number" tickFormatter={compactMoney} tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="shortName" width={105} tick={{ fontSize: 11 }} /><Tooltip formatter={(value, name) => [money(value), name]} labelFormatter={(_, payload) => payload?.[0]?.payload?.name || ''} /><Legend wrapperStyle={{ fontSize: 12 }} /><Bar dataKey="washerCommissions" name="Lavador" stackId="roles" fill="#10b981" isAnimationActive={false} /><Bar dataKey="supervisorCommissions" name="Encargado" stackId="roles" fill="#f59e0b" isAnimationActive={false} /></BarChart></ResponsiveContainer></div><details className="mt-3 text-sm"><summary className="cursor-pointer font-medium text-slate-600">Ver importes por empleado</summary><div className="mt-3"><CarwashTable testId="carwash-report-employees" rows={data.employees.map((row) => ({ ...row, id: row.employeeId }))} columns={[{ key: 'name', label: 'Empleado', render: (row) => row.name }, { key: 'washes', label: 'Lavados', render: (row) => row.washes }, { key: 'washer', label: 'Lavador', render: (row) => money(row.washerCommissions) }, { key: 'supervisor', label: 'Encargado', render: (row) => money(row.supervisorCommissions) }, { key: 'total', label: 'Total', render: (row) => money(row.commissions) }]} emptyMessage="Sin comisiones." /></div></details></> : <CarwashEmpty message="No hay comisiones devengadas en este período." />}
    </CarwashPanel>
  </>
}
